-- AlterTable
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "dryRun" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "inputHash" TEXT;
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "outputJson" JSONB;
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "ExecutionLog" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMP(3);
