/**
 * Terraform HCL drafter.
 *
 * Converts a Phase 102 policy preview (AWS SCP JSON / Azure Policy
 * JSON / GCP Org Policy JSON) into ready-to-PR Terraform HCL.
 *
 * Output is intentionally minimal — just the resource block. The
 * operator pastes it into their existing module structure and
 * adjusts var names / provider blocks to match their conventions.
 *
 * Hard rules:
 *   - Pure string templating. No tf init / plan / apply ever.
 *   - Input policy JSON is embedded with jsonencode(...) → terraform
 *     re-encodes safely; no manual escaping required.
 *   - Resource name is derived from the policy label, slugified to
 *     terraform-safe identifiers.
 */

export type TerraformCloud = "aws" | "azure" | "gcp";

export interface TerraformDraftInput {
  cloud: TerraformCloud;
  /** Short human label, e.g. "Deny PutBucketPublicAccessBlock weakening". */
  label: string;
  /** The policy preview JSON string. */
  policyJson: string;
}

export interface TerraformDraft {
  resourceName: string;
  hcl: string;
  applyHint: string;
  warnings: string[];
}

export function draftTerraform(input: TerraformDraftInput): TerraformDraft {
  const slug = slugify(input.label);
  const policyHcl = embedAsHcl(input.policyJson);

  switch (input.cloud) {
    case "aws":
      return {
        resourceName: `aws_organizations_policy.${slug}`,
        hcl: [
          `resource "aws_organizations_policy" "${slug}" {`,
          `  name        = "${input.label.replace(/"/g, '\\"').slice(0, 128)}"`,
          `  description = "Generated by Axiom (Phase 102/107) — review before apply."`,
          `  type        = "SERVICE_CONTROL_POLICY"`,
          `  content     = jsonencode(${policyHcl})`,
          `}`,
        ].join("\n"),
        applyHint:
          "After pasting, attach the SCP to the target OU via `aws_organizations_policy_attachment`. Run `terraform plan` first; SCPs can lock out admin actions if conditions are wrong.",
        warnings: validateAwsPolicy(input.policyJson),
      };
    case "azure":
      return {
        resourceName: `azurerm_policy_definition.${slug}`,
        hcl: [
          `resource "azurerm_policy_definition" "${slug}" {`,
          `  name         = "${slug}"`,
          `  policy_type  = "Custom"`,
          `  mode         = "Indexed"`,
          `  display_name = "${input.label.replace(/"/g, '\\"').slice(0, 128)}"`,
          `  policy_rule  = jsonencode(${embedAzurePolicyRule(input.policyJson)})`,
          `}`,
        ].join("\n"),
        applyHint:
          "Assign the definition to a management group with `azurerm_management_group_policy_assignment`. Test with `terraform plan` and Azure Policy compliance scan before broad enforcement.",
        warnings: validateAzurePolicy(input.policyJson),
      };
    case "gcp":
      return {
        resourceName: `google_org_policy_policy.${slug}`,
        hcl: [
          `resource "google_org_policy_policy" "${slug}" {`,
          `  name   = "organizations/\${var.org_id}/policies/${extractGcpConstraint(input.policyJson)}"`,
          `  parent = "organizations/\${var.org_id}"`,
          `  spec {`,
          `    rules {`,
          `      enforce = "TRUE"`,
          `    }`,
          `  }`,
          `}`,
        ].join("\n"),
        applyHint:
          "Set var.org_id to your GCP org id. `google_org_policy_policy` requires the org-policies API enabled + roles/orgpolicy.policyAdmin on the caller.",
        warnings: validateGcpPolicy(input.policyJson),
      };
  }
}

// ---------------------------------------------------------------------------
// Slug + embed helpers
// ---------------------------------------------------------------------------

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60) || "policy";
}

/** Embed JSON safely inside an HCL jsonencode(...) wrapper. */
function embedAsHcl(json: string): string {
  // Parse + re-stringify with 2-space indent. If parse fails, fall back
  // to embedding the raw string (still works because jsonencode handles
  // any JSON-encoded string).
  try {
    const obj = JSON.parse(json);
    return objectToHcl(obj, 1);
  } catch {
    return JSON.stringify(json);
  }
}

/** Azure Policy uses a nested `properties.policyRule` structure — extract just the rule. */
function embedAzurePolicyRule(json: string): string {
  try {
    const obj = JSON.parse(json) as { properties?: { policyRule?: unknown } };
    const rule = obj.properties?.policyRule ?? obj;
    return objectToHcl(rule, 1);
  } catch {
    return JSON.stringify(json);
  }
}

/** GCP Org Policy constraint name extraction. */
function extractGcpConstraint(json: string): string {
  try {
    const obj = JSON.parse(json) as { name?: string };
    if (typeof obj.name === "string") {
      return obj.name.replace(/^policies\//, "");
    }
  } catch {
    /* fall through */
  }
  return "compute.requireOsLogin"; // safe placeholder operators rename
}

/** Convert a parsed JSON value into HCL-compatible literal that jsonencode() can wrap. */
function objectToHcl(value: unknown, depth: number): string {
  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);

  if (value === null) return "null";
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const inner = value.map((v) => `${childIndent}${objectToHcl(v, depth + 1)}`).join(",\n");
    return `[\n${inner}\n${indent}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    const inner = entries
      .map(([k, v]) => `${childIndent}${jsonKey(k)} = ${objectToHcl(v, depth + 1)}`)
      .join(",\n");
    return `{\n${inner}\n${indent}}`;
  }

  return JSON.stringify(String(value));
}

function jsonKey(key: string): string {
  // HCL accepts identifier keys; anything with non-word chars must be quoted.
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : JSON.stringify(key);
}

// ---------------------------------------------------------------------------
// Per-cloud sanity checks
// ---------------------------------------------------------------------------

function validateAwsPolicy(json: string): string[] {
  const warnings: string[] = [];
  try {
    const obj = JSON.parse(json) as { Version?: string; Statement?: unknown };
    if (obj.Version !== "2012-10-17") warnings.push("Version field is not '2012-10-17' (AWS IAM standard).");
    if (!obj.Statement) warnings.push("Statement is missing — policy will be a no-op.");
  } catch {
    warnings.push("Policy JSON failed to parse — review before applying.");
  }
  return warnings;
}

function validateAzurePolicy(json: string): string[] {
  const warnings: string[] = [];
  try {
    const obj = JSON.parse(json) as { properties?: { policyRule?: unknown; mode?: string } };
    if (!obj.properties?.policyRule) warnings.push("properties.policyRule is missing.");
    if (!obj.properties?.mode) warnings.push("properties.mode is missing — defaulting to 'Indexed'.");
  } catch {
    warnings.push("Azure Policy JSON failed to parse.");
  }
  return warnings;
}

function validateGcpPolicy(json: string): string[] {
  const warnings: string[] = [];
  try {
    const obj = JSON.parse(json) as { name?: string; spec?: unknown };
    if (!obj.name) warnings.push("Policy name is missing — constraint path placeholder used.");
    if (!obj.spec) warnings.push("spec block is missing.");
  } catch {
    warnings.push("GCP Org Policy JSON failed to parse.");
  }
  return warnings;
}
