// Comprehensive guides data - matching iOS EnhancedGuideData.swift
import { FormGuide, StepDetail, DifficultyLevel } from "./types";

export const guides: FormGuide[] = [
  {
    id: "i130",
    title: "📝 I-130: Petition for Alien Relative",
    overview: "The I-130 petition establishes the family relationship between you and your relative. This is typically the first step in the family-based immigration process.",
    estimatedTime: "9-33 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i130-1",
        title: "Gather required documents",
        description: "Before you start, collect proof of relationship (e.g. marriage certificate, birth certificate), passport-style photos of both you and your relative, copies of passports or ID, and any other evidence that shows your family tie. Having these ready makes filling out the form easier.",
        tips: ["Use a checklist so you don’t miss anything", "Get certified or original copies where USCIS requires them", "Keep one set of copies for yourself"],
        warnings: ["Missing documents can lead to delays or a Request for Evidence (RFE)", "Names on all documents should match exactly"],
      },
      {
        id: "i130-2",
        title: "Create or log in to your USCIS account",
        description: "Go to my.uscis.gov and create an account (or log in if you already have one). You’ll use this account to file the form, pay the fee, and track your case.",
        link: "https://my.uscis.gov",
        tips: ["Use a strong password and turn on two-factor authentication", "Use an email you check often – USCIS sends updates there"],
        warnings: ["Don’t share your account with anyone", "Keep your login details safe – you’ll need them for the whole process"],
      },
      {
        id: "i130-3",
        title: "Fill out Form I-130",
        description: "Complete the I-130 petition form. You can do it online at my.uscis.gov (recommended) or download the paper form from the USCIS website. Answer every question; if something doesn’t apply, write “N/A”.",
        link: "https://www.uscis.gov/i-130",
        tips: ["Use the exact names as on birth certificates and passports", "Double-check dates and addresses", "Save your work often if filing online"],
        warnings: ["Mistakes can slow down processing", "False information can lead to denial and future immigration problems"],
      },
      {
        id: "i130-4",
        title: "Prepare proof of relationship",
        description: "Organize the documents that prove your relationship. For a spouse: marriage certificate, photos, joint bills or lease. For a parent/child: birth certificate, photos. USCIS wants to see that the relationship is real.",
        tips: ["Include a short cover letter listing what you’re sending", "Use clear labels or tabs so officers can find things easily", "More evidence is better than less – but keep it organized"],
        warnings: ["Translations of non-English documents must be certified", "Photos and documents should be recent and relevant"],
      },
      {
        id: "i130-5",
        title: "Upload supporting documents",
        description: "Attach or upload your proof of relationship and any other required evidence to your application. Scan documents clearly (300 DPI or higher) and save as PDF so they’re easy to read.",
        tips: ["Scan in color if the document has color", "Name files clearly (e.g. marriage_certificate.pdf)", "Check file size limits on the USCIS site"],
        warnings: ["Blurry or unreadable documents may be rejected", "Don’t send originals unless USCIS asks for them – send copies"],
      },
      {
        id: "i130-6",
        title: "Review everything before submitting",
        description: "Go through the form and all attachments one more time. Check names, dates, and addresses. Make sure you didn’t skip any questions and that your evidence matches what you wrote on the form.",
        tips: ["Have someone else look at it if possible", "Compare the form to the official USCIS instructions", "Confirm the filing fee amount on uscis.gov before paying"],
        warnings: ["Once you submit, you can’t take it back – fix errors now", "Wrong fee amount can cause your package to be sent back"],
      },
      {
        id: "i130-7",
        title: "Submit and pay the fee",
        description: "Submit your form and pay the filing fee ($535 as of 2024 – check uscis.gov for the current amount). Online filing usually gets a receipt faster than mail.",
        link: "https://www.uscis.gov/fees",
        tips: ["Pay online when possible for faster processing", "Save the payment confirmation and receipt", "If mailing, use a trackable service"],
        warnings: ["Insufficient payment can delay or reject your case", "Fees change – always confirm the amount on the USCIS website"],
      },
      {
        id: "i130-8",
        title: "Receive Form I-797 (receipt notice)",
        description: "USCIS will send you a receipt (Form I-797) that they got your petition. It will include a receipt number. Keep this safe – you need it to track your case and for future steps.",
        tips: ["Make several copies of the receipt", "The receipt number usually has 3 letters followed by numbers (e.g. IOE1234567890)", "Add the receipt number to your records and calendar"],
        warnings: ["If you don’t get a receipt within a few weeks, check with USCIS", "Don’t lose the receipt number – you’ll use it for years"],
      },
      {
        id: "i130-9",
        title: "Track your case and respond to RFE if you get one",
        description: "Use your receipt number to check case status at egov.uscis.gov. If USCIS sends a Request for Evidence (RFE), they need more information or documents. Reply by the deadline given in the letter.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Check status regularly or sign up for email/text updates", "If you get an RFE, read it carefully and send exactly what they ask for", "Keep a copy of everything you send in response to an RFE"],
        warnings: ["Missing the RFE deadline can cause your case to be denied", "Answer only what they ask – don’t send unrelated documents"],
      },
      {
        id: "i130-10",
        title: "After approval: what happens next",
        description: "When your I-130 is approved, the next step depends on where your relative lives. If abroad: the case goes to the National Visa Center (NVC), then to an embassy for an interview. If in the U.S.: they may be able to apply for a green card (I-485). USCIS will send approval notice with next steps.",
        link: "https://www.uscis.gov/family",
        tips: ["Save the approval notice – you’ll need it for the next stage", "Start gathering documents for NVC or I-485 as soon as you can", "Processing times vary – check USCIS and State Department for current wait times"],
        warnings: ["Don’t skip the next step – approval is only one part of the process", "Fees and forms for NVC or I-485 are separate"],
      },
    ],
  },
  {
    id: "k3",
    title: "💍 K-3 Visa: Spouse Visa (Optional)",
    overview: "Optional visa for spouses of U.S. citizens. Must file I-130 first. K-3 processing is often slower than I-130, and many K-3 applications become unnecessary if I-130 is approved first.",
    estimatedTime: "12-24 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "k3-1",
        title: "File Form I-130 first (and get receipt)",
        description: "You must have filed Form I-130 for your spouse before you can file for K-3. Wait until you have the I-130 receipt notice from USCIS – you’ll need that receipt number for the K-3 application.",
        link: "https://www.uscis.gov/i-130",
        tips: ["Save your I-130 receipt number – you’ll enter it on Form I-129F", "I-130 doesn’t have to be approved yet, just filed and receipted"],
        warnings: ["K-3 is optional; many couples skip it because I-130 often approves first", "K-3 processing is often slower than I-130"],
      },
      {
        id: "k3-2",
        title: "Gather documents for I-129F (K-3)",
        description: "Collect marriage certificate, passport-style photos of both of you, proof of U.S. citizenship, and your I-130 receipt. You’ll attach these when you file Form I-129F for K-3.",
        tips: ["Use the same type of evidence as for I-130 (marriage cert, photos)", "Have the I-130 receipt notice in front of you when filling I-129F"],
        warnings: ["Wrong or missing documents can delay or deny the K-3", "You’ll pay another fee ($535) for I-129F"],
      },
      {
        id: "k3-3",
        title: "Fill out Form I-129F for K-3",
        description: "Complete Form I-129F and select or indicate that you’re applying for the K-3 nonimmigrant visa. Enter your I-130 receipt number so USCIS can link the two cases.",
        link: "https://www.uscis.gov/i-129f",
        tips: ["File I-129F as soon as you have the I-130 receipt", "Double-check the I-130 receipt number – one typo can delay everything"],
        warnings: ["K-3 is rarely used now; I-130 alone often reaches the visa stage first", "Additional $535 fee – check uscis.gov for current amount"],
      },
      {
        id: "k3-4",
        title: "Submit Form I-129F and pay the fee",
        description: "Submit your I-129F package to the address or lockbox listed in the form instructions. Pay the required fee (e.g. $535 – confirm on uscis.gov). Keep a copy of everything you send.",
        link: "https://www.uscis.gov/fees",
        tips: ["Send by a trackable method so you know USCIS received it", "Save the payment confirmation and mailing receipt"],
        warnings: ["Wrong fee or wrong address can cause rejection or long delays", "Fees change – always check the USCIS website"],
      },
      {
        id: "k3-5",
        title: "Track both I-130 and K-3 cases",
        description: "Use your receipt numbers to check status for both the I-130 and the I-129F (K-3) at egov.uscis.gov. Often the I-130 is approved first, and the K-3 path is then unnecessary.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Check both receipt numbers regularly", "If I-130 is approved first, NVC will contact you for the next step – you may not need K-3"],
        warnings: ["K-3 does not guarantee faster entry; I-130 approval often comes first", "Don’t assume K-3 will be processed before I-130"],
      },
      {
        id: "k3-6",
        title: "After approval: next steps",
        description: "If K-3 is approved, your spouse will get instructions for the visa interview abroad. If I-130 is approved first, the case usually goes to the National Visa Center (NVC) for an immigrant visa instead. Follow the notice you receive from USCIS or the Department of State.",
        link: "https://travel.state.gov/content/travel/en/us-visas/immigrate/family-immigration.html",
        tips: ["Save all approval notices and case numbers", "NVC or the consulate will tell you which forms and fees are next"],
        warnings: ["Next steps and fees are separate from the I-130 and K-3 filing", "Processing times vary – check USCIS and State Department for current wait times"],
      },
    ],
  },
  {
    id: "i485",
    title: "🟢 I-485: Adjustment of Status (Green Card)",
    overview: "Application to adjust status to permanent resident (green card holder) while in the United States. Must have approved I-130 or other qualifying petition.",
    estimatedTime: "8-33 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i485-1",
        title: "Verify you’re eligible to adjust status",
        description: "You must be in the U.S., have an approved I-130 (or I-140 or other qualifying petition), and be admissible. Some people need a waiver for past overstays or other issues. Check the official I-485 instructions to confirm you qualify.",
        link: "https://www.uscis.gov/i-485",
        tips: ["You must be physically present in the U.S. when you file", "Your immigrant petition (e.g. I-130) must already be approved", "Overstays or unauthorized work may require a waiver – consider talking to a lawyer"],
        warnings: ["Certain criminal or immigration violations can make you inadmissible", "Eligibility rules are strict – when in doubt, check uscis.gov or consult an attorney"],
      },
      {
        id: "i485-2",
        title: "Gather required documents",
        description: "Collect birth certificate, passport, I-94, passport-style photos, and your approved I-130 (or other petition) notice. You’ll also need the Affidavit of Support (I-864) from your sponsor and possibly I-693 (medical) – see next steps.",
        tips: ["Make a checklist from the USCIS I-485 page", "Get certified translations for any document not in English", "Keep one full copy of everything for yourself"],
        warnings: ["Missing documents lead to Request for Evidence (RFE) and delays", "Names and dates must match on all forms and documents"],
      },
      {
        id: "i485-3",
        title: "Complete medical exam (I-693)",
        description: "Schedule a medical exam with a USCIS-approved civil surgeon (find one at my.uscis.gov/findadoctor). The doctor fills out Form I-693 and seals it in an envelope. Do not open that envelope – send it sealed with your I-485 or bring it to the interview if instructed.",
        link: "https://my.uscis.gov/findadoctor",
        tips: ["Bring your vaccination records to avoid extra shots", "Book early – civil surgeon appointments can fill up", "The sealed envelope stays sealed until USCIS opens it"],
        warnings: ["Only a USCIS-designated civil surgeon can do this exam", "The medical can expire – check current validity rules on uscis.gov"],
      },
      {
        id: "i485-4",
        title: "Fill out Form I-485",
        description: "Complete the Application to Register Permanent Residence or Adjust Status (I-485). It’s long and detailed – take your time. Answer every question; if something doesn’t apply, write “N/A”. Use the correct edition of the form from uscis.gov.",
        link: "https://www.uscis.gov/i-485",
        tips: ["Use black ink if filing on paper", "Include your A-number and I-94 number if you have them", "Save your work often if filing online"],
        warnings: ["False or incomplete information can lead to denial and deportation", "Use only the current form version from the USCIS website"],
      },
      {
        id: "i485-5",
        title: "Prepare Affidavit of Support (I-864) and other supporting forms",
        description: "Your sponsor (usually the person who filed the I-130) must complete Form I-864 to show they have enough income to support you. Gather their tax returns, pay stubs, and any other evidence required. Include I-693 (medical) if you’re submitting it with the package.",
        link: "https://www.uscis.gov/i-864",
        tips: ["Sponsor must meet income guidelines – check the I-864 instructions", "Organize everything with a cover letter and tabs so nothing is missed", "Double-check that every form is signed and dated"],
        warnings: ["Missing or incomplete I-864 will result in an RFE", "Income requirements are strict – a joint sponsor may be needed"],
      },
      {
        id: "i485-6",
        title: "Review everything before submitting",
        description: "Go through the I-485, I-864, I-693 (if included), and all supporting documents. Check names, dates, and addresses. Confirm the fee amount on uscis.gov and that you’re sending the package to the correct address.",
        tips: ["Have someone else review the forms if possible", "Compare your answers to the official form instructions", "Confirm fee and mailing address – both can change"],
        warnings: ["Wrong fee or wrong filing location can delay or reject your case", "Once submitted, you can’t take it back – fix errors now"],
      },
      {
        id: "i485-7",
        title: "Submit I-485 and pay the fee",
        description: "Send your complete I-485 package to the address in the form instructions (or file online if available). Pay the required fee (e.g. around $1,225 for most – use the USCIS fee calculator for the exact amount).",
        link: "https://www.uscis.gov/fees",
        tips: ["Use a trackable mailing method", "Keep copies and proof of mailing", "Pay online when possible for faster receipt"],
        warnings: ["Incorrect fee will cause rejection or delay", "Fees change – always use the current amount on uscis.gov"],
      },
      {
        id: "i485-8",
        title: "Receive receipt and attend biometrics",
        description: "USCIS will send a receipt (I-797) with a receipt number. Later you’ll get a notice to go to an Application Support Center for fingerprints and photo (biometrics). Go to the appointment on the date given.",
        tips: ["Save the receipt number – you’ll use it to track your case", "Bring the biometrics notice and ID to your appointment", "Reschedule if you can’t make it – follow the instructions on the notice"],
        warnings: ["Missing your biometrics appointment can delay or harm your case", "Don’t ignore any notice from USCIS"],
      },
      {
        id: "i485-9",
        title: "Respond to RFE if you get one, and prepare for interview",
        description: "If USCIS sends a Request for Evidence (RFE), respond by the deadline with exactly what they ask for. Many I-485 cases also require an interview – you’ll get a notice with the date, time, and what to bring.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Answer RFEs completely and by the deadline", "For the interview, bring originals of key documents and a copy of your application", "Check case status online and read every notice carefully"],
        warnings: ["Missing the RFE deadline can lead to denial", "Failing to show up for the interview can result in denial"],
      },
      {
        id: "i485-10",
        title: "After approval: get your green card",
        description: "If your I-485 is approved, you’ll receive your green card by mail. Keep the approval notice and the card safe. The card is proof of your lawful permanent resident status.",
        tips: ["Check the card for errors – name, date of birth, etc. If wrong, file I-90 to correct", "Renew the card before it expires (usually 10 years, or 2 years if conditional)"],
        warnings: ["Don’t lose your green card – you need it for work and re-entry to the U.S.", "Conditional residents (e.g. marriage-based) must file I-751 to remove conditions"],
      },
    ],
  },
  {
    id: "i129f",
    title: "💑 I-129F: Petition for Alien Fiancé(e)",
    overview: "Used to bring your fiancé(e) to the United States to get married. The couple must marry within 90 days of the fiancé(e)'s arrival.",
    estimatedTime: "8-12 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i129f-1",
        title: "Gather required documents",
        description: "Collect passport-style photos of both you and your fiancé(e), proof that you met in person in the last 2 years (photos, tickets, affidavits), and evidence of your relationship (messages, calls, visits). You’ll also need proof of U.S. citizenship (e.g. passport or birth certificate).",
        tips: ["USCIS requires proof you met in person – have dates and evidence ready", "Passport photos must meet the size and style on the form instructions", "More relationship evidence (photos, messages, plans) strengthens the case"],
        warnings: ["If you haven’t met in person, you generally don’t qualify for the fiancé(e) petition", "All non-English documents need certified translations"],
      },
      {
        id: "i129f-2",
        title: "Proof of meeting in person",
        description: "You must show you met each other in person at least once in the 2 years before filing (with limited exceptions). Use photos together, travel records, passport stamps, or signed affidavits from people who know you both.",
        tips: ["Label photos with date and place", "Affidavits should state how the person knows you and that you met", "Passport stamps and boarding passes help prove travel and meeting"],
        warnings: ["Failure to prove meeting can result in denial", "Waivers for the meeting requirement are very rare"],
      },
      {
        id: "i129f-3",
        title: "Fill out Form I-129F",
        description: "Complete the Petition for Alien Fiancé(e) with accurate information about you (the U.S. citizen petitioner) and your fiancé(e) (the beneficiary). Answer every question; if something doesn’t apply, write “N/A”.",
        link: "https://www.uscis.gov/i-129f",
        tips: ["Use exact names as on passports and birth certificates", "List all previous marriages and how they ended", "Sign and date where required"],
        warnings: ["False information can lead to denial and future immigration problems", "Mistakes can cause long delays or Request for Evidence (RFE)"],
      },
      {
        id: "i129f-4",
        title: "Prepare your evidence package",
        description: "Organize proof of meeting, relationship evidence, photos, and any required documents (e.g. divorce decrees if either of you was married before). Follow the form instructions for what to include and how to order it.",
        tips: ["Use a cover letter listing what you’re sending", "Make copies of everything and keep a full set for yourself", "Check the latest form instructions – requirements can change"],
        warnings: ["Missing evidence often leads to RFE or denial", "Don’t send originals of irreplaceable documents – send copies unless instructed otherwise"],
      },
      {
        id: "i129f-5",
        title: "Review and double-check before sending",
        description: "Go through the form and attachments again. Confirm names, dates, and addresses. Make sure you didn’t skip any questions and that the filing fee is correct (e.g. $535 – check uscis.gov for current amount).",
        tips: ["Have someone else look at the form if possible", "Verify the lockbox or filing address in the instructions", "Confirm fee amount – wrong payment can get the package returned"],
        warnings: ["Wrong fee or wrong address can reject or delay your case", "Once you mail it, you can’t take it back – fix errors now"],
      },
      {
        id: "i129f-6",
        title: "Submit the petition and pay the fee",
        description: "Mail your complete I-129F package to the USCIS lockbox address in the form instructions. Pay the required fee (e.g. $535 – confirm on uscis.gov). Use a trackable method and keep proof of mailing.",
        link: "https://www.uscis.gov/fees",
        tips: ["Keep a copy of the entire package and the mailing receipt", "Note the lockbox can take a few weeks to send you a receipt notice", "Save the receipt number as soon as you get it"],
        warnings: ["Incorrect fee or wrong address will delay or reject your case", "Fees change – always check the USCIS website"],
      },
      {
        id: "i129f-7",
        title: "Receive receipt and track your case",
        description: "USCIS will send a receipt (Form I-797) with a receipt number. Use that number to check case status at egov.uscis.gov. If they send a Request for Evidence (RFE), respond by the deadline with exactly what they ask for.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Sign up for case updates by email or text if offered", "Respond to any RFE quickly and completely", "Keep all notices in a safe place – you’ll need them for the next stage"],
        warnings: ["Missing the RFE deadline can result in denial", "Don’t lose your receipt number – the beneficiary will need it for the visa interview"],
      },
      {
        id: "i129f-8",
        title: "After approval: NVC and visa interview",
        description: "When the I-129F is approved, the case goes to the National Visa Center (NVC), then to the U.S. embassy or consulate where your fiancé(e) will have a visa interview. They’ll need to complete additional forms, pay fees, and bring documents to the interview.",
        link: "https://travel.state.gov/content/travel/en/us-visas/immigrate/family-immigration/fiance-k-1-visa.html",
        tips: ["Save the approval notice – NVC and the consulate will need the case number", "Your fiancé(e) must marry you within 90 days of entering the U.S. on the K-1 visa", "After marriage, they file I-485 to get a green card"],
        warnings: ["Fees and forms for NVC and the interview are separate from the I-129F", "Not marrying within 90 days can affect their status – follow the rules carefully"],
      },
    ],
  },
  {
    id: "i765",
    title: "💼 I-765: Employment Authorization Document (EAD)",
    overview: "Application for Employment Authorization. Allows you to work legally in the U.S. while your immigration case is pending.",
    estimatedTime: "3-6 months",
    difficulty: DifficultyLevel.Easy,
    steps: [
      {
        id: "i765-1",
        title: "Determine if you’re eligible",
        description: "Work authorization depends on your status or pending application. Common categories: pending I-485 (green card), asylum applicant, F-1 student with OPT, DACA, or other specific categories. Check the I-765 instructions to see which category fits you.",
        link: "https://www.uscis.gov/i-765",
        tips: ["Each category has its own requirements and documents", "If you have a pending I-485, you usually qualify for an EAD while you wait", "DACA, asylum, and F-1 OPT have their own eligibility rules"],
        warnings: ["Working without authorization is illegal and can lead to deportation", "Not every immigration status allows work – check the official list"],
      },
      {
        id: "i765-2",
        title: "Gather required documents",
        description: "Collect passport-style photos, a copy of your I-94 (or other proof of status), and any form that shows your eligibility (e.g. I-485 receipt, asylum receipt). The exact list depends on your eligibility category – see the form instructions.",
        tips: ["Use the I-765 instructions to build a checklist for your category", "Photos must meet the size and style on the form", "Keep copies of everything you send"],
        warnings: ["Missing documents often lead to Request for Evidence (RFE) or denial", "Wrong category or wrong documents can delay or deny your case"],
      },
      {
        id: "i765-3",
        title: "Fill out Form I-765",
        description: "Complete the Application for Employment Authorization. The most important part is choosing the correct eligibility category – this decides whether you qualify, what documents you need, and how long processing takes.",
        link: "https://www.uscis.gov/i-765",
        tips: ["Select the correct eligibility category – this is critical", "Include your A-number if you have one", "Answer every question; if something doesn’t apply, write “N/A”"],
        warnings: ["Wrong eligibility category can result in denial", "False information can lead to denial and future immigration problems"],
      },
      {
        id: "i765-4",
        title: "Review and double-check before submitting",
        description: "Go through the form and attachments again. Confirm your eligibility category, names, dates, and that the fee is correct. If you’re filing with I-485, the I-765 fee may be included – check the current rules on uscis.gov.",
        tips: ["Compare your answers to the official instructions", "Confirm fee amount – it varies by category and whether you’re filing with I-485", "Verify the correct mailing address or online filing option"],
        warnings: ["Wrong fee or wrong address can reject or delay your case", "Once submitted, you can’t take it back – fix errors now"],
      },
      {
        id: "i765-5",
        title: "Submit the application and pay the fee",
        description: "File your I-765 with USCIS (online or by mail, depending on category). Pay the required fee (e.g. $410 for standalone, or included with I-485 – check uscis.gov for current amounts and fee waiver rules).",
        link: "https://www.uscis.gov/fees",
        tips: ["If filing with I-485, I-765 fee is often included – confirm in the I-485 instructions", "Use a trackable method if mailing", "Save the payment confirmation and mailing receipt"],
        warnings: ["Incorrect fee will cause rejection", "Fee waivers are limited – check eligibility on uscis.gov"],
      },
      {
        id: "i765-6",
        title: "Receive receipt and track your case",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. You may be called for biometrics. If they send an RFE, respond by the deadline.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Save the receipt number – you’ll use it to track and for employers", "Some categories get automatic 180-day extension of work authorization – check the rules for your category"],
        warnings: ["Don’t work until you have the EAD in hand (unless your category allows it)", "Missing an RFE deadline can result in denial"],
      },
      {
        id: "i765-7",
        title: "After approval: use and renew your EAD",
        description: "When approved, you’ll receive your EAD card by mail. It shows your photo and expiration date. Don’t work past the expiration date. If you need to renew, file a new I-765 well before the card expires.",
        tips: ["Keep a copy of the card and approval notice", "Renew several months before expiration – processing can take months", "Some categories get automatic extensions while renewal is pending – check uscis.gov"],
        warnings: ["Working after the EAD expires can be illegal and harm your immigration case", "Lost or stolen cards should be reported and replaced with a new I-765"],
      },
    ],
  },
  {
    id: "i131",
    title: "✈️ I-131: Advance Parole (Travel Document)",
    overview: "Allows immigrants with pending I-485 applications to travel outside the United States and return without abandoning their adjustment of status application.",
    estimatedTime: "3-6 months",
    difficulty: DifficultyLevel.Easy,
    steps: [
      {
        id: "i131-1",
        title: "Determine if you need Advance Parole",
        description: "If you have a pending I-485 (green card application) and need to leave the U.S., you generally need Advance Parole to return without abandoning your application. If you leave without it, USCIS may consider your I-485 abandoned.",
        link: "https://www.uscis.gov/i-131",
        tips: ["Only needed if you’re leaving the U.S. while I-485 is pending", "You can file I-131 together with I-485 – no extra fee in that case", "Some other statuses also use I-131 for travel documents – check the form instructions"],
        warnings: ["Leaving without Advance Parole (when required) can abandon your I-485", "Advance Parole does not guarantee re-entry – CBP can still deny entry"],
      },
      {
        id: "i131-2",
        title: "Gather required documents",
        description: "Collect passport-style photos, a copy of your I-485 receipt (if you have a pending I-485), and any document that shows your current status (e.g. I-94). You may also include a short letter explaining your reason for travel.",
        tips: ["Photos must meet the size and style on the form instructions", "If filing with I-485, you often don’t need a separate fee – check the I-485 instructions", "Keep copies of everything you send"],
        warnings: ["Missing documents can lead to Request for Evidence (RFE) or denial", "Wrong category or wrong fee can delay or reject your case"],
      },
      {
        id: "i131-3",
        title: "Fill out Form I-131",
        description: "Complete the Application for Travel Document. Select the correct type (e.g. Advance Parole for pending I-485). Answer every question; if something doesn’t apply, write “N/A”. Explain your reason for travel briefly if asked.",
        link: "https://www.uscis.gov/i-131",
        tips: ["Select the correct application type – Advance Parole vs. Re-entry Permit vs. Refugee Travel Document", "Include your A-number and I-485 receipt number if you have them", "Be honest about your travel plans – false information can result in denial"],
        warnings: ["Wrong application type can result in denial", "False information can harm your immigration case"],
      },
      {
        id: "i131-4",
        title: "Review and submit the application",
        description: "Go through the form and attachments again. Confirm the fee (often $0 if filed with I-485 – check uscis.gov). Submit to the correct address or file online if available.",
        link: "https://www.uscis.gov/fees",
        tips: ["If filing with I-485, I-131 fee is usually included – confirm in the I-485 instructions", "If filing alone (e.g. after I-485 was filed separately), confirm the current fee", "Use a trackable mailing method and keep proof of mailing"],
        warnings: ["Incorrect fee or wrong address can reject or delay your case", "Don’t travel until you have the Advance Parole document in hand (unless you’re not required to have it)"],
      },
      {
        id: "i131-5",
        title: "Receive receipt and wait for approval",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. Processing can take several months. Do not travel outside the U.S. until you have the Advance Parole document unless your category allows it.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Save the receipt number to track your case", "If you have an emergency, you may request expedited processing – see uscis.gov", "The Advance Parole document will have an expiration date – don’t return after it expires"],
        warnings: ["Traveling before you have Advance Parole (when required) can abandon your I-485", "Re-entry is at the discretion of CBP – follow the rules and bring your documents"],
      },
      {
        id: "i131-6",
        title: "Using Advance Parole when you travel",
        description: "When you travel, bring your Advance Parole document (and passport, I-485 receipt, etc.). Present them when you return to the U.S. You’re still in “parole” status – you’re not a permanent resident until the I-485 is approved.",
        tips: ["Keep copies of your Advance Parole and I-485 receipt in a safe place when traveling", "Don’t stay abroad longer than necessary – long trips can sometimes raise questions", "After I-485 approval, you won’t need Advance Parole for future travel – use your green card"],
        warnings: ["Advance Parole does not guarantee re-entry – CBP can still deny entry", "Don’t use Advance Parole to work abroad – it’s for travel only"],
      },
    ],
  },
  {
    id: "i140",
    title: "🏢 I-140: Employment-Based Immigrant Petition",
    overview: "Immigrant Petition for Alien Worker. Filed by employer on behalf of employee for employment-based green card.",
    estimatedTime: "6-12 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i140-1",
        title: "Determine which employment category applies",
        description: "Identify the right employment-based category: EB-1 (extraordinary ability, outstanding researcher, or multinational manager), EB-2 (advanced degree or exceptional ability), EB-3 (skilled worker or professional), etc. Each has different requirements and evidence.",
        link: "https://www.uscis.gov/i-140",
        tips: ["EB-1 often does not require a labor certification (PERM)", "EB-2 and EB-3 usually require a PERM labor certification from the Department of Labor first", "Your employer and, if needed, an immigration attorney can help choose the category"],
        warnings: ["Wrong category can result in denial", "Some categories have long visa backlogs – check the Visa Bulletin"],
      },
      {
        id: "i140-2",
        title: "Complete PERM labor certification (if required)",
        description: "For EB-2 and EB-3, the employer must complete the PERM process with the Department of Labor before filing I-140. This includes testing the labor market and getting a certified labor certification.",
        link: "https://www.dol.gov/agencies/eta/foreign-labor",
        tips: ["PERM is done by the employer, not the employee", "PERM can take several months – plan ahead", "A denied PERM usually means I-140 cannot be filed for that job"],
        warnings: ["PERM is complex – employers often use an attorney", "PERM denial or audit can delay or block the I-140"],
      },
      {
        id: "i140-3",
        title: "Gather evidence for the I-140",
        description: "The employer (petitioner) gathers evidence for the chosen category: degree evaluations, letters of experience, job offer letter, PERM certification (if applicable), and any other required proof that the employee and job qualify.",
        tips: ["EB-1: focus on awards, publications, and recognition", "EB-2/EB-3: focus on degree, experience, and PERM", "Organize evidence with a cover letter and tabs"],
        warnings: ["Missing or weak evidence leads to Request for Evidence (RFE) or denial", "Evidence must match the category selected"],
      },
      {
        id: "i140-4",
        title: "Complete Form I-140",
        description: "The employer (petitioner) fills out Form I-140, Immigrant Petition for Alien Worker. The employee is the beneficiary. Select the correct preference category and attach all required evidence.",
        link: "https://www.uscis.gov/i-140",
        tips: ["The employer signs and files the form – not the employee", "Include all supporting documents listed in the instructions", "Answer every question; if something doesn’t apply, write “N/A”"],
        warnings: ["False or incomplete information can result in denial and future immigration problems", "Missing evidence will cause RFE or denial"],
      },
      {
        id: "i140-5",
        title: "Review and submit the petition",
        description: "Go through the form and evidence again. Confirm the fee ($700 for standard – check uscis.gov). The employer submits the I-140 to USCIS. Premium processing ($2,500) is available for faster adjudication in many categories.",
        link: "https://www.uscis.gov/fees",
        tips: ["Premium processing (if available) gives a 15-day response for an extra $2,500", "Use the correct mailing address or online filing if available", "Keep a full copy of the petition and proof of mailing"],
        warnings: ["Incorrect fee will cause rejection", "Fees and premium availability can change – check uscis.gov"],
      },
      {
        id: "i140-6",
        title: "Receive receipt and track the case",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. If they send an RFE, the employer must respond by the deadline with the requested evidence.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Save the receipt number – the employee will need it for I-485 or consular processing", "RFE responses must be complete and on time", "Approval does not by itself give a green card – next step is I-485 or consular processing"],
        warnings: ["Missing the RFE deadline can result in denial", "Approval date can affect “priority date” for visa availability – keep the approval notice"],
      },
      {
        id: "i140-7",
        title: "After approval: next steps (I-485 or consular processing)",
        description: "Once the I-140 is approved, the employee can apply for a green card: either by filing I-485 (if in the U.S. and a visa number is available) or through consular processing (if abroad). Check the Visa Bulletin for when a visa number is available.",
        link: "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
        tips: ["Check the Visa Bulletin for your category and country – “priority date” must be current", "I-485 and consular processing have their own forms, fees, and steps", "Keep the I-140 approval notice – you’ll need it for the next stage"],
        warnings: ["A visa number must be available before you can get a green card", "Fees and forms for I-485 or consular processing are separate from the I-140"],
      },
    ],
  },
  {
    id: "i751",
    title: "💚 I-751: Remove Conditions on Residence",
    overview: "Petition to Remove Conditions on Residence. Converts your 2-year conditional green card into a 10-year permanent green card.",
    estimatedTime: "18-24 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i751-1",
        title: "Know the 90-day filing window",
        description: "You must file I-751 within 90 days before your conditional green card expires. Filing earlier than 90 days before expiration can get the package rejected; filing after the card expires can put you out of status.",
        link: "https://www.uscis.gov/i-751",
        tips: ["Mark the first day of the 90-day window on your calendar", "File as soon as you’re in the window – don’t wait until the last day", "If you file on time, your status and work authorization continue while the case is pending"],
        warnings: ["Filing late can result in loss of status and removal proceedings", "Filing too early (more than 90 days before expiration) will be rejected"],
      },
      {
        id: "i751-2",
        title: "Gather relationship evidence",
        description: "Collect evidence that your marriage is real and ongoing for the full 2-year period since you got your conditional green card. Include joint bank statements, lease or mortgage, bills, insurance, photos, affidavits from friends or family, and anything else that shows you live together and share a life.",
        tips: ["Cover the entire 2-year period – not just recent months", "Joint finances (bank, taxes, insurance) are strong evidence", "Photos, travel, and affidavits help show a real relationship"],
        warnings: ["Insufficient evidence can result in denial and removal", "Evidence must span the full 2-year period"],
      },
      {
        id: "i751-3",
        title: "Organize your evidence",
        description: "Organize documents with a cover letter and tabs so USCIS can follow along. Group by type (financial, housing, travel, affidavits). Make copies and keep a full set for yourself.",
        tips: ["Use a cover letter listing what you’re sending", "Label sections clearly", "Include certified translations for any document not in English"],
        warnings: ["Disorganized or missing evidence can lead to Request for Evidence (RFE) or denial", "Don’t send originals of irreplaceable documents – send copies unless instructed"],
      },
      {
        id: "i751-4",
        title: "Complete Form I-751",
        description: "Fill out the Petition to Remove Conditions on Residence. If you’re still married and living together, you usually file jointly – both you and your spouse must sign the form. If you’re divorced, widowed, or filing a waiver, follow the instructions for that situation.",
        link: "https://www.uscis.gov/i-751",
        tips: ["Answer every question truthfully", "If filing jointly, both spouses must sign", "If filing a waiver (abuse, hardship, etc.), include a detailed statement and evidence"],
        warnings: ["False information can result in denial and deportation", "Filing a waiver (not jointly) is harder – you need strong evidence of good faith marriage or qualifying waiver grounds"],
      },
      {
        id: "i751-5",
        title: "Review and submit the petition",
        description: "Go through the form and evidence again. Confirm the fee (e.g. $680 – check uscis.gov for current amount) and the correct mailing address. Submit within the 90-day window.",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and address on uscis.gov – both can change", "Use a trackable mailing method and keep proof of mailing", "Keep a full copy of the package and the mailing receipt"],
        warnings: ["Incorrect fee or wrong address can reject or delay your case", "Filing after the card expires can put you out of status"],
      },
      {
        id: "i751-6",
        title: "Receive receipt and extension letter",
        description: "USCIS will send a receipt and usually an extension letter that extends your green card status (often by 48 months) while the I-751 is pending. Keep the receipt and extension with your green card when traveling or showing proof of status.",
        tips: ["Carry the receipt and extension letter with your expired green card", "You may be called for biometrics – go to the appointment on the date given", "Check case status at egov.uscis.gov with your receipt number"],
        warnings: ["Don’t lose the extension letter – you need it until the new card is issued", "Missing biometrics or an interview can delay or harm your case"],
      },
      {
        id: "i751-7",
        title: "Respond to RFE or attend interview if required",
        description: "If USCIS sends a Request for Evidence (RFE), respond by the deadline with exactly what they ask for. Some cases require an interview – you’ll get a notice with the date, time, and what to bring.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Answer RFEs completely and on time", "For the interview, bring originals of key documents and a copy of your petition", "Both spouses should attend if you filed jointly"],
        warnings: ["Missing the RFE deadline can result in denial", "Failing to show up for the interview can result in denial"],
      },
      {
        id: "i751-8",
        title: "After approval: 10-year green card",
        description: "When your I-751 is approved, you’ll receive a new 10-year permanent green card by mail. You’re no longer “conditional” – you’re a lawful permanent resident. Keep the card safe and renew before it expires.",
        tips: ["Check the card for errors – if wrong, file I-90 to correct", "Renew the card before it expires (usually 10 years)", "You may be eligible to apply for citizenship (N-400) after 5 years (or 3 if married to a U.S. citizen)"],
        warnings: ["Don’t lose your green card – you need it for work and re-entry to the U.S.", "Losing status can affect future citizenship applications"],
      },
    ],
  },
  {
    id: "i90",
    title: "🆔 I-90: Renew or Replace Green Card",
    overview: "Application to Replace Permanent Resident Card. File if your green card is expiring, lost, stolen, damaged, or contains errors.",
    estimatedTime: "12-18 months",
    difficulty: DifficultyLevel.Easy,
    steps: [
      {
        id: "i90-1",
        title: "Determine if you need I-90",
        description: "File I-90 if your green card is expiring (renewal), lost, stolen, damaged, or has errors (replacement or correction). For renewal, you can file as early as 6 months before expiration. For lost or stolen, file as soon as possible and consider filing a police report.",
        link: "https://www.uscis.gov/i-90",
        tips: ["Renewal: File up to 6 months before the card expires", "Lost/stolen: File right away and keep a copy of the police report if you file one", "Correction: File if the card has a wrong name, date, or other error"],
        warnings: ["Letting the card expire can cause problems with work and travel", "Lost or stolen cards should be reported – USCIS may ask"],
      },
      {
        id: "i90-2",
        title: "Gather required documents",
        description: "Collect a copy of your current green card (if you have it – front and back), passport-style photos, and any other document the form instructions ask for (e.g. police report for lost/stolen, court order for name change).",
        tips: ["Photos must meet the size and style on the form instructions", "If the card is lost or stolen, include a copy if you have one; otherwise explain in the form", "Keep copies of everything you send"],
        warnings: ["Missing or wrong documents can lead to Request for Evidence (RFE) or denial", "Wrong “reason for filing” can delay processing"],
      },
      {
        id: "i90-3",
        title: "Complete Form I-90",
        description: "Fill out the Application to Replace Permanent Resident Card. Choose the correct reason: renewal, lost/stolen, damaged, or correction. Answer every question; if something doesn’t apply, write “N/A”.",
        link: "https://www.uscis.gov/i-90",
        tips: ["Online filing is usually faster and lets you track the case right away", "Select the correct reason for filing – renewal vs. replacement vs. correction", "Use the exact name and date of birth as on your current card or passport"],
        warnings: ["False information can result in denial", "Wrong reason can delay or complicate your case"],
      },
      {
        id: "i90-4",
        title: "Review and submit the application",
        description: "Go through the form and attachments again. Confirm the fee (e.g. $540 – check uscis.gov for current amount and fee waiver rules). Submit online or by mail to the address in the instructions.",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and mailing address on uscis.gov", "Use a trackable method if mailing and keep proof of mailing", "Fee waiver is available in some cases – see the form instructions"],
        warnings: ["Incorrect fee will cause rejection", "Fees change – always check the USCIS website"],
      },
      {
        id: "i90-5",
        title: "Receive receipt and attend biometrics",
        description: "USCIS will send a receipt with a receipt number. You may be scheduled for biometrics (fingerprints and photo). Go to the appointment on the date given. Your receipt may also extend your status while the application is pending.",
        tips: ["Save the receipt number to track your case at egov.uscis.gov", "Bring the biometrics notice and ID to your appointment", "If you’re renewing, the receipt often extends your status – check the notice"],
        warnings: ["Missing your biometrics appointment can delay your case", "Don’t travel without proof of status if your old card has expired and you’re waiting for the new one"],
      },
      {
        id: "i90-6",
        title: "After approval: receive your new card",
        description: "When your I-90 is approved, you’ll receive your new green card by mail. Check it for errors (name, date of birth, etc.). If something is wrong, you may need to file again or contact USCIS.",
        tips: ["Keep the new card safe – you need it for work and re-entry to the U.S.", "Renew again before the new card expires (usually 10 years)", "If you’re eligible, you can apply for citizenship (N-400) with a valid green card"],
        warnings: ["Don’t lose your new card – replacing it again requires another I-90 and fee", "Using an expired card for work or travel can cause problems"],
      },
    ],
  },
  {
    id: "n400",
    title: "🇺🇸 N-400: Naturalization (U.S. Citizenship)",
    overview: "Application for Naturalization. Become a U.S. citizen after meeting residency and other requirements.",
    estimatedTime: "6-12 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "n400-1",
        title: "Verify you meet eligibility requirements",
        description: "You must be at least 18, have been a permanent resident for 5 years (or 3 years if married to a U.S. citizen and meeting other rules), meet physical presence (e.g. 30 months in the U.S. in the last 5 years), and have good moral character. Check the official N-400 instructions to confirm you qualify.",
        link: "https://www.uscis.gov/n-400",
        tips: ["5-year rule: Green card for 5 years before filing", "3-year rule: Married to U.S. citizen for 3 years and living together", "Physical presence: 30 months in U.S. out of 60 (or 18 out of 36 for 3-year rule)"],
        warnings: ["Criminal history or long absences can make you ineligible", "Unpaid taxes or failure to file can affect good moral character", "When in doubt, check uscis.gov or consult an attorney"],
      },
      {
        id: "n400-2",
        title: "Gather required documents",
        description: "Collect your green card, passport, tax returns (or transcripts) for the required period, travel records (if you traveled outside the U.S.), and any other document the N-400 instructions ask for (e.g. marriage certificate if applying under the 3-year rule).",
        tips: ["Use the N-400 instructions checklist for your situation", "Get certified translations for any document not in English", "Keep copies of everything you send"],
        warnings: ["Missing documents can lead to Request for Evidence (RFE) or denial", "Tax and travel history must match what you put on the form"],
      },
      {
        id: "n400-3",
        title: "Complete Form N-400",
        description: "Fill out the Application for Naturalization. Answer every question truthfully. You must disclose all arrests, citations, and violations – even if they were dismissed or expunged. False or incomplete answers can result in denial and deportation.",
        link: "https://www.uscis.gov/n-400",
        tips: ["Answer all questions – if something doesn’t apply, write “N/A” or “None”", "List all trips outside the U.S. during the required period", "Disclose all criminal history – failing to disclose is considered fraud"],
        warnings: ["False information can result in denial, deportation, and permanent bar", "Failing to disclose criminal history is fraud and can lead to loss of citizenship later"],
      },
      {
        id: "n400-4",
        title: "Review and submit the application",
        description: "Go through the form and attachments again. Confirm the fee (e.g. $640 plus $85 biometrics – check uscis.gov for current amount and fee waiver rules). Submit online or by mail to the address in the instructions.",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and mailing address on uscis.gov", "Use a trackable method if mailing and keep proof of mailing", "Fee waiver is available in some cases – see the form instructions"],
        warnings: ["Incorrect fee will cause rejection", "Fees change – always check the USCIS website"],
      },
      {
        id: "n400-5",
        title: "Receive receipt and attend biometrics",
        description: "USCIS will send a receipt with a receipt number. You’ll be scheduled for biometrics (fingerprints and photo). Go to the appointment on the date given.",
        tips: ["Save the receipt number to track your case at egov.uscis.gov", "Bring the biometrics notice and ID to your appointment", "Reschedule if you can’t make it – follow the instructions on the notice"],
        warnings: ["Missing your biometrics appointment can delay your case", "Don’t ignore any notice from USCIS"],
      },
      {
        id: "n400-6",
        title: "Study for the citizenship test",
        description: "Prepare for the civics test (up to 10 questions from a list of 100) and the English test (reading, writing, speaking). Study materials are on the USCIS website. Some applicants (e.g. age 65+ with 20 years as a permanent resident) may get special consideration for the civics test.",
        link: "https://www.uscis.gov/citizenship/learners/study-test",
        tips: ["Study the 100 civics questions – you’ll be asked up to 10", "Practice English reading and writing – you’ll have to read and write one sentence", "You can retake the failed portion within 90 days of the interview"],
        warnings: ["Failing the test requires a retake – prepare well", "You must pass both civics and English (unless you qualify for an exemption)"],
      },
      {
        id: "n400-7",
        title: "Attend the naturalization interview",
        description: "USCIS will send a notice with the date, time, and place of your interview. Bring the notice, your green card, passport, and any other document the notice asks for. You’ll be asked questions about your application, and you’ll take the civics and English tests.",
        tips: ["Bring originals of key documents and a copy of your N-400", "Answer questions truthfully and consistently with your form", "If you don’t understand a question, ask the officer to repeat or clarify"],
        warnings: ["Failing to show up can result in denial", "False or inconsistent answers can result in denial and possible removal"],
      },
      {
        id: "n400-8",
        title: "Take the Oath of Allegiance",
        description: "If your application is approved, you’ll be scheduled for an Oath of Allegiance ceremony. At the ceremony you’ll turn in your green card and become a U.S. citizen. You’ll receive a Certificate of Naturalization.",
        link: "https://www.uscis.gov/citizenship/citizenship-through-naturalization",
        tips: ["Bring the oath ceremony notice and your green card to the ceremony", "After the oath, you can apply for a U.S. passport", "Keep your Certificate of Naturalization safe – you’ll need it for passport and other purposes"],
        warnings: ["Don’t miss the oath ceremony – follow the instructions on the notice", "You are not a citizen until you take the oath – don’t claim citizenship before then"],
      },
    ],
  },
  {
    id: "i601",
    title: "🛡️ I-601: Waiver of Inadmissibility",
    overview: "Application for Waiver of Grounds of Inadmissibility. Used to overcome certain bars to immigration.",
    estimatedTime: "8-12 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i601-1",
        title: "Understand which inadmissibility ground applies",
        description: "Identify the ground of inadmissibility that applies to you: unlawful presence, fraud, criminal conviction, health, or another ground. Each ground has different waiver requirements. Not all grounds can be waived – some criminal convictions make you permanently inadmissible.",
        link: "https://www.uscis.gov/i-601",
        tips: ["Common grounds: unlawful presence (3 or 10 year bar), fraud, certain criminal convictions", "The consulate or USCIS will tell you which ground applies", "Consider consulting an immigration attorney – waivers are complex"],
        warnings: ["Not all grounds can be waived", "Some criminal convictions have no waiver – check the law"],
      },
      {
        id: "i601-2",
        title: "Identify your qualifying relative",
        description: "For many waivers (e.g. unlawful presence), you must show extreme hardship to a qualifying relative – usually a U.S. citizen or lawful permanent resident (LPR) spouse or parent. The hardship must be to them, not only to you.",
        tips: ["Qualifying relative is usually a U.S. citizen or LPR spouse or parent", "Hardship to children or other family may be considered but isn’t always enough", "The relative’s situation (health, finances, dependents) is what matters"],
        warnings: ["Weak or wrong qualifying relative can result in denial", "Hardship must be extreme – “difficult” is often not enough"],
      },
      {
        id: "i601-3",
        title: "Gather extreme hardship evidence",
        description: "Collect evidence of extreme hardship to your qualifying relative: medical records, financial records, proof of dependency, country conditions, and affidavits. The hardship must be extreme – not just difficult or sad. Focus on what would happen to the qualifying relative if you’re not granted the waiver.",
        tips: ["Medical: conditions that need your care or that would worsen if the relative had to move", "Financial: loss of income, cost of separation, cost of relocating", "Emotional: mental health, family separation, impact on children"],
        warnings: ["Weak hardship evidence usually results in denial", "Evidence must focus on the qualifying relative, not only on you"],
      },
      {
        id: "i601-4",
        title: "Complete Form I-601",
        description: "Fill out the Application for Waiver of Grounds of Inadmissibility. Explain clearly which inadmissibility ground applies and why the waiver should be granted (e.g. extreme hardship to qualifying relative, or rehabilitation for certain criminal grounds). Be thorough and honest.",
        link: "https://www.uscis.gov/i-601",
        tips: ["Explain the inadmissibility ground and your eligibility for a waiver", "Detail the extreme hardship or rehabilitation with specific facts", "Attach a clear index of evidence and organize documents with tabs"],
        warnings: ["Weak or vague explanation can result in denial", "False information is fraud and can lead to permanent bar"],
      },
      {
        id: "i601-5",
        title: "Review and submit the application",
        description: "Go through the form and evidence again. Confirm the fee (e.g. $930 – check uscis.gov) and where to file (often depends on whether you’re in the U.S. or abroad and which agency has your case). Submit with a complete waiver package.",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and filing location on uscis.gov – it depends on your case", "Include a cover letter and index of evidence", "Keep a full copy of the package and proof of mailing"],
        warnings: ["Incorrect fee or wrong address can reject or delay your case", "Incomplete packages often lead to Request for Evidence (RFE) or denial"],
      },
      {
        id: "i601-6",
        title: "Receive receipt and track the case",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. Processing can take many months. If they send an RFE, respond by the deadline with exactly what they ask for.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Save the receipt number – you’ll need it for the consulate or next step", "RFE responses must be complete and on time", "Approval doesn’t by itself give you a visa – you still must complete the immigrant visa process"],
        warnings: ["Missing the RFE deadline can result in denial", "Waiver approval is one step – follow all instructions from the consulate or USCIS"],
      },
    ],
  },
  {
    id: "i601a",
    title: "🔐 I-601A: Provisional Unlawful Presence Waiver",
    overview: "Provisional Unlawful Presence Waiver. Allows you to get waiver approved before leaving U.S. for consular interview, reducing time abroad.",
    estimatedTime: "6-12 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i601a-1",
        title: "Understand the provisional waiver",
        description: "The I-601A lets you apply for a waiver of unlawful presence before you leave the U.S. for your consular interview. If approved, you go abroad for the interview with the waiver already in hand, which can shorten the time you’re away from family. You must still attend the consular interview.",
        link: "https://www.uscis.gov/i-601a",
        tips: ["Only for unlawful presence inadmissibility – not for fraud or other grounds", "You must have an approved I-130 or I-140 (or certain other petitions)", "You must be in the U.S. when you file the I-601A"],
        warnings: ["Other inadmissibility grounds (fraud, criminal, etc.) are not waived by I-601A", "The waiver can be revoked if circumstances change or if you’re found inadmissible for another reason"],
      },
      {
        id: "i601a-2",
        title: "Verify you’re eligible",
        description: "You must have an approved I-130 or I-140 (or other qualifying petition), only unlawful presence as the inadmissibility ground, and a qualifying relative (U.S. citizen or LPR spouse or parent) who would suffer extreme hardship if you’re not granted the waiver. You must be in the U.S. when you file.",
        tips: ["Your immigrant visa case must be at the Department of State (NVC) stage or you must have a pending I-130/I-140", "Only unlawful presence can be waived – other grounds disqualify you", "Extreme hardship must be to the qualifying relative, not only to you"],
        warnings: ["Other inadmissibility grounds disqualify you for I-601A", "You must be physically in the U.S. when you file"],
      },
      {
        id: "i601a-3",
        title: "Gather extreme hardship evidence",
        description: "Collect evidence of extreme hardship to your U.S. citizen or LPR spouse or parent: medical records, financial records, proof of dependency, country conditions, and affidavits. The hardship must be extreme – not just difficult. Focus on what would happen to the qualifying relative if you’re not granted the waiver.",
        tips: ["Medical: conditions that need your care or that would worsen if the relative had to move or be alone", "Financial: loss of income, cost of separation, cost of relocating", "Emotional: mental health, family separation, impact on children"],
        warnings: ["Weak hardship evidence usually results in denial", "Hardship must be to the qualifying relative, not only to you"],
      },
      {
        id: "i601a-4",
        title: "Complete Form I-601A",
        description: "Fill out the Application for Provisional Unlawful Presence Waiver. Explain your unlawful presence and why your qualifying relative would suffer extreme hardship if you’re not granted the waiver. Be thorough and honest.",
        link: "https://www.uscis.gov/i-601a",
        tips: ["Explain unlawful presence clearly (dates, circumstances)", "Detail extreme hardship to the qualifying relative with specific facts", "Attach a clear index of evidence and organize documents with tabs"],
        warnings: ["Weak or vague explanation can result in denial", "False information is fraud and can lead to permanent bar"],
      },
      {
        id: "i601a-5",
        title: "Review and submit the application",
        description: "Go through the form and evidence again. Confirm the fee (e.g. $630 – check uscis.gov) and where to file. Submit with a complete waiver package. You must be in the U.S. when you file.",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and filing address on uscis.gov", "Include a cover letter and index of evidence", "Keep a full copy of the package and proof of mailing"],
        warnings: ["Incorrect fee or wrong address can reject or delay your case", "Leaving the U.S. before filing or before a decision can affect your case – follow the rules"],
      },
      {
        id: "i601a-6",
        title: "Receive receipt and wait for a decision",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. Processing can take many months. Do not leave the U.S. for your consular interview until the I-601A is approved (or you may lose the benefit). If they send an RFE, respond by the deadline.",
        link: "https://egov.uscis.gov/casestatus",
        tips: ["Save the receipt number – you’ll need it for NVC and the consulate", "RFE responses must be complete and on time", "After approval, follow NVC and consulate instructions for the visa interview"],
        warnings: ["Leaving the U.S. before I-601A is approved can affect your case – check the rules", "Approval doesn’t guarantee a visa – you must still pass the consular interview"],
      },
      {
        id: "i601a-7",
        title: "After approval: attend consular interview",
        description: "When your I-601A is approved, you’ll get instructions from the Department of State (NVC) and the U.S. embassy or consulate. You must attend the immigrant visa interview abroad. Bring the I-601A approval notice and all other required documents.",
        link: "https://travel.state.gov/content/travel/en/us-visas/immigrate.html",
        tips: ["Bring the I-601A approval notice to the interview", "Follow all instructions from NVC and the consulate", "If you’re found inadmissible for another reason, the I-601A waiver may not help"],
        warnings: ["You must still attend the consular interview – the I-601A only waives unlawful presence", "Other inadmissibility grounds can still result in visa denial"],
      },
    ],
  },
  {
    id: "i821d",
    title: "🎓 I-821D: DACA (Deferred Action for Childhood Arrivals)",
    overview: "Application for Deferred Action for Childhood Arrivals. Provides temporary protection from deportation and work authorization for eligible individuals who arrived in the U.S. as children.",
    estimatedTime: "3-6 months",
    difficulty: DifficultyLevel.Moderate,
    steps: [
      {
        id: "i821d-1",
        title: "Verify you meet DACA eligibility",
        description: "You must have arrived in the U.S. before your 16th birthday, have continuous residence since June 15, 2007, have been present in the U.S. on June 15, 2012, be in school or have graduated or have a GED (or be an honorably discharged veteran), and have no serious criminal history. Check the official DACA page for the full list and any updates.",
        link: "https://www.uscis.gov/daca",
        tips: ["Arrival before 16 is required", "Continuous residence since June 15, 2007 – gaps can disqualify you", "Present in U.S. on June 15, 2012"],
        warnings: ["Serious criminal history or certain offenses make you ineligible", "Eligibility rules and program status can change – check uscis.gov", "When in doubt, consult an immigration attorney"],
      },
      {
        id: "i821d-2",
        title: "Gather required documents",
        description: "Collect evidence of arrival date (passport, I-94, travel records), continuous residence (school records, medical records, bills, affidavits), education (diplomas, transcripts, GED certificate), and identity (passport, birth certificate, school ID). All non-English documents need certified translations.",
        tips: ["Use the USCIS DACA checklist to build your list", "Cover the full period from June 15, 2007 to the present", "More evidence is better – gaps in proof can lead to denial"],
        warnings: ["Missing documents can result in denial or Request for Evidence (RFE)", "All documents not in English must be translated and certified"],
      },
      {
        id: "i821d-3",
        title: "Complete Form I-821D",
        description: "Fill out the Consideration of Deferred Action for Childhood Arrivals (I-821D) with accurate information about your arrival, residence, education, and background. You must disclose all arrests, citations, and violations – even if they were dismissed or expunged.",
        link: "https://www.uscis.gov/i-821d",
        tips: ["Answer every question truthfully", "List all arrests and citations – failing to disclose is fraud", "Double-check dates and addresses"],
        warnings: ["False information can result in denial and potential removal", "Failing to disclose criminal history is considered fraud"],
      },
      {
        id: "i821d-4",
        title: "Complete Form I-765 for work authorization",
        description: "Fill out the Application for Employment Authorization (I-765) and select the DACA category (c)(33). You must file I-765 together with I-821D to get work authorization. Without I-765, you won’t receive an EAD.",
        link: "https://www.uscis.gov/i-765",
        tips: ["File I-765 with I-821D in the same package", "Select eligibility category (c)(33) for DACA", "Include passport-style photos and any other required documents for I-765"],
        warnings: ["I-765 must be filed with I-821D – missing I-765 means no work authorization", "Wrong category can result in denial"],
      },
      {
        id: "i821d-5",
        title: "Review and submit the application",
        description: "Go through I-821D, I-765, and all supporting documents again. Confirm the fee (e.g. $495 – check uscis.gov for current amount and fee waiver rules). Submit to the address in the instructions (or file online if available).",
        link: "https://www.uscis.gov/fees",
        tips: ["Confirm fee and mailing address on uscis.gov", "Use a trackable method if mailing and keep proof of mailing", "Keep a full copy of the package and the mailing receipt"],
        warnings: ["Incorrect fee will cause rejection", "Fees and filing options can change – check the USCIS website"],
      },
      {
        id: "i821d-6",
        title: "Receive receipt and attend biometrics",
        description: "USCIS will send a receipt with a receipt number. Use it to check case status at egov.uscis.gov. You’ll be scheduled for biometrics (fingerprints and photo). Go to the appointment on the date given.",
        tips: ["Save the receipt number to track your case", "Bring the biometrics notice and ID to your appointment", "Reschedule if you can’t make it – follow the instructions on the notice"],
        warnings: ["Missing your biometrics appointment can delay your case", "Don’t ignore any notice from USCIS"],
      },
      {
        id: "i821d-7",
        title: "After approval: receive EAD and renew on time",
        description: "When your DACA and I-765 are approved, you’ll receive your Employment Authorization Document (EAD) by mail. DACA and the EAD are valid for a limited period (e.g. 2 years). You must renew before they expire – file a new I-821D and I-765 well before the expiration date.",
        link: "https://www.uscis.gov/daca",
        tips: ["Renew several months before your EAD expires – processing can take months", "Keep copies of your EAD and approval notices", "Check uscis.gov for renewal deadlines and any policy changes"],
        warnings: ["Letting DACA or the EAD expire can affect your status and work authorization", "Renewal rules and deadlines can change – stay updated on uscis.gov"],
      },
    ],
  },
];
