-- Phase 441/442/443/450 — ReleaseOps foundation.
--
-- Adds:
--   Phase 441: Application, Component, Repository, Environment,
--              BranchEnvironmentPolicy + enums ComponentKind,
--              GitProvider, EnvironmentTier
--   Phase 442: Release, ReleaseReadinessSnapshot, ReleaseEvidencePack
--              (status / riskLevel / readiness blockers stored as
--              strings + JSON to keep migration light)
--   Phase 443: PolicyRule, PolicyViolation
--
-- SQL was generated by `prisma migrate diff --from-empty
-- --to-schema-datamodel prisma/schema.prisma --script` and trimmed
-- to just the new tables / indexes / foreign keys — byte-for-byte
-- what Prisma would emit, so the generated client matches the DB.

CREATE TYPE "ComponentKind" AS ENUM ('app', 'infra', 'data_pipeline', 'connector', 'database', 'dag', 'iac', 'artifact');
CREATE TYPE "GitProvider" AS ENUM ('github', 'gitlab', 'azuredevops', 'other');
CREATE TYPE "EnvironmentTier" AS ENUM ('dev', 'test', 'qa', 'uat', 'stage', 'preprod', 'prod');
CREATE TABLE "Application" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "ownerTeamLabel" TEXT,
    "businessTier" TEXT,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Application_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Component" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "kind" "ComponentKind" NOT NULL,
    "repositoryId" TEXT,
    "dependsOnIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ownerTeamLabel" TEXT,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Component_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Repository" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "provider" "GitProvider" NOT NULL,
    "remoteOwner" TEXT NOT NULL,
    "remoteName" TEXT NOT NULL,
    "remoteUrl" TEXT NOT NULL,
    "defaultBranch" TEXT NOT NULL DEFAULT 'main',
    "protectedBranches" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codeownersPresent" BOOLEAN NOT NULL DEFAULT false,
    "prTemplatePresent" BOOLEAN NOT NULL DEFAULT false,
    "repoFlavor" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Repository_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Environment" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "tier" "EnvironmentTier" NOT NULL,
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "changeWindowRuleJson" JSONB,
    "approvalPolicyId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Environment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BranchEnvironmentPolicy" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "repositoryId" TEXT NOT NULL,
    "environmentId" TEXT NOT NULL,
    "branchPattern" TEXT NOT NULL,
    "requireReleaseTag" BOOLEAN NOT NULL DEFAULT false,
    "requireCodeowners" BOOLEAN NOT NULL DEFAULT false,
    "requirePrLink" BOOLEAN NOT NULL DEFAULT false,
    "requireChangeTicket" BOOLEAN NOT NULL DEFAULT false,
    "priority" INTEGER NOT NULL DEFAULT 100,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BranchEnvironmentPolicy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Release" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "targetEnvironmentId" TEXT,
    "releaseTag" TEXT,
    "commitSha" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "scopeFinalizedAt" TIMESTAMP(3),
    "scopeFinalizedByUserId" TEXT,
    "rollbackReferenceReleaseId" TEXT,
    "plannedWindowStart" TIMESTAMP(3),
    "plannedWindowEnd" TIMESTAMP(3),
    "actualDeployStart" TIMESTAMP(3),
    "actualDeployEnd" TIMESTAMP(3),
    "summary" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdByUserId" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Release_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReleaseReadinessSnapshot" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "releaseId" TEXT NOT NULL,
    "evaluatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "branchGovernance" INTEGER NOT NULL,
    "changeCompliance" INTEGER NOT NULL,
    "artifactTraceability" INTEGER NOT NULL,
    "secretTraceability" INTEGER NOT NULL,
    "rollbackReadiness" INTEGER NOT NULL,
    "communicationReadiness" INTEGER NOT NULL,
    "driftRisk" INTEGER NOT NULL,
    "manualReconciliation" INTEGER NOT NULL,
    "overallScore" INTEGER NOT NULL,
    "riskLevel" TEXT NOT NULL,
    "blockersJson" JSONB NOT NULL,
    "evaluationSource" TEXT NOT NULL,

    CONSTRAINT "ReleaseReadinessSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReleaseEvidencePack" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "releaseId" TEXT NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "signedAt" TIMESTAMP(3),
    "contentHash" TEXT,
    "contentJson" JSONB NOT NULL,
    "exportRefsJson" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReleaseEvidencePack_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PolicyRule" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "blocking" BOOLEAN NOT NULL DEFAULT false,
    "exceptionAllowed" BOOLEAN NOT NULL DEFAULT false,
    "approverRole" TEXT,
    "evidenceRequired" BOOLEAN NOT NULL DEFAULT false,
    "autoRemediationKey" TEXT,
    "description" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "source" TEXT NOT NULL DEFAULT 'seed',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PolicyRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PolicyViolation" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "ruleId" TEXT NOT NULL,
    "releaseId" TEXT NOT NULL,
    "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'open',
    "message" TEXT NOT NULL,
    "remediation" TEXT,
    "exceptionGrantedByUserId" TEXT,
    "exceptionGrantedAt" TIMESTAMP(3),
    "contextJson" JSONB,

    CONSTRAINT "PolicyViolation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Application_organizationId_idx" ON "Application"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "Application_organizationId_slug_key" ON "Application"("organizationId", "slug");

-- CreateIndex
CREATE INDEX "Component_organizationId_idx" ON "Component"("organizationId");

-- CreateIndex
CREATE INDEX "Component_kind_idx" ON "Component"("kind");

-- CreateIndex
CREATE UNIQUE INDEX "Component_applicationId_slug_key" ON "Component"("applicationId", "slug");

-- CreateIndex
CREATE INDEX "Repository_organizationId_idx" ON "Repository"("organizationId");

-- CreateIndex
CREATE INDEX "Repository_provider_idx" ON "Repository"("provider");

-- CreateIndex
CREATE UNIQUE INDEX "Repository_organizationId_provider_remoteOwner_remoteName_key" ON "Repository"("organizationId", "provider", "remoteOwner", "remoteName");

-- CreateIndex
CREATE INDEX "Environment_organizationId_idx" ON "Environment"("organizationId");

-- CreateIndex
CREATE INDEX "Environment_tier_idx" ON "Environment"("tier");

-- CreateIndex
CREATE UNIQUE INDEX "Environment_organizationId_slug_key" ON "Environment"("organizationId", "slug");

-- CreateIndex
CREATE INDEX "BranchEnvironmentPolicy_organizationId_idx" ON "BranchEnvironmentPolicy"("organizationId");

-- CreateIndex
CREATE INDEX "BranchEnvironmentPolicy_environmentId_idx" ON "BranchEnvironmentPolicy"("environmentId");

-- CreateIndex
CREATE UNIQUE INDEX "BranchEnvironmentPolicy_repositoryId_environmentId_branchPa_key" ON "BranchEnvironmentPolicy"("repositoryId", "environmentId", "branchPattern");

-- CreateIndex
CREATE INDEX "Release_organizationId_idx" ON "Release"("organizationId");

-- CreateIndex
CREATE INDEX "Release_applicationId_idx" ON "Release"("applicationId");

-- CreateIndex
CREATE INDEX "Release_status_idx" ON "Release"("status");

-- CreateIndex
CREATE INDEX "Release_targetEnvironmentId_idx" ON "Release"("targetEnvironmentId");

-- CreateIndex
CREATE UNIQUE INDEX "Release_organizationId_applicationId_releaseTag_key" ON "Release"("organizationId", "applicationId", "releaseTag");

-- CreateIndex
CREATE INDEX "ReleaseReadinessSnapshot_releaseId_evaluatedAt_idx" ON "ReleaseReadinessSnapshot"("releaseId", "evaluatedAt");

-- CreateIndex
CREATE INDEX "ReleaseReadinessSnapshot_organizationId_evaluatedAt_idx" ON "ReleaseReadinessSnapshot"("organizationId", "evaluatedAt");

-- CreateIndex
CREATE UNIQUE INDEX "ReleaseEvidencePack_releaseId_key" ON "ReleaseEvidencePack"("releaseId");

-- CreateIndex
CREATE INDEX "ReleaseEvidencePack_organizationId_generatedAt_idx" ON "ReleaseEvidencePack"("organizationId", "generatedAt");

-- CreateIndex
CREATE INDEX "PolicyRule_organizationId_idx" ON "PolicyRule"("organizationId");

-- CreateIndex
CREATE INDEX "PolicyRule_severity_idx" ON "PolicyRule"("severity");

-- CreateIndex
CREATE UNIQUE INDEX "PolicyRule_organizationId_key_key" ON "PolicyRule"("organizationId", "key");

-- CreateIndex
CREATE INDEX "PolicyViolation_organizationId_status_idx" ON "PolicyViolation"("organizationId", "status");

-- CreateIndex
CREATE INDEX "PolicyViolation_releaseId_idx" ON "PolicyViolation"("releaseId");

-- CreateIndex
CREATE INDEX "PolicyViolation_ruleId_status_idx" ON "PolicyViolation"("ruleId", "status");

ALTER TABLE "Component" ADD CONSTRAINT "Component_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Component" ADD CONSTRAINT "Component_repositoryId_fkey" FOREIGN KEY ("repositoryId") REFERENCES "Repository"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BranchEnvironmentPolicy" ADD CONSTRAINT "BranchEnvironmentPolicy_repositoryId_fkey" FOREIGN KEY ("repositoryId") REFERENCES "Repository"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BranchEnvironmentPolicy" ADD CONSTRAINT "BranchEnvironmentPolicy_environmentId_fkey" FOREIGN KEY ("environmentId") REFERENCES "Environment"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReleaseReadinessSnapshot" ADD CONSTRAINT "ReleaseReadinessSnapshot_releaseId_fkey" FOREIGN KEY ("releaseId") REFERENCES "Release"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReleaseEvidencePack" ADD CONSTRAINT "ReleaseEvidencePack_releaseId_fkey" FOREIGN KEY ("releaseId") REFERENCES "Release"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PolicyViolation" ADD CONSTRAINT "PolicyViolation_ruleId_fkey" FOREIGN KEY ("ruleId") REFERENCES "PolicyRule"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
