export type {
  RunAgentInput,
  ApprovalInput,
  AgentRunResult,
  AgentTrigger,
  AgentRunStatus,
  AgentFinding,
  FindingCategory,
  FindingSeverity,
  ActionDisposition,
  AgentRecommendation,
  AgentActionPlan,
  ApprovalItem,
  AgentApplyResult,
  AgentMessage,
  AgentMessageType,
} from "./types";

export { runAgent, handleApproval } from "./runAgent";
export { generateSnapshot } from "./providerRegistry";
export type { SnapshotGenerator } from "./providerRegistry";
export { classifyDisposition, findingToRecommendation, priorityScore, classifyDispositionWithPrefs, findingToRecommendationWithPrefs, priorityScoreWithPrefs } from "./prioritizer";
export { loadPreferences, savePreferences, filterIgnoredFindings, applyDispositionPolicy, applyRiskTolerance, categoryBoost, agentTone } from "./preferences";
export type { OrgPreferences, PreferenceUpdates } from "./preferences";
export { buildRecommendations } from "./recommendationBuilder";
export type { RichRecommendation } from "./recommendationBuilder";
export * as agentMessages from "./messageBuilder";
export { runFirstExperience } from "./onboarding";
export type { OnboardingInput, OnboardingSummary, OnboardingFinding, OnboardingNextStep } from "./onboarding";
export {
  resolvePolicy,
  resolveDisposition,
  applyAutopilotToRecommendations,
  changeAutopilotMode,
  logAutopilotAction,
  loadAutopilotMode,
  isEscalation,
  getModeConfirmationCopy,
  MODE_COPY,
  MODE_ORDER,
} from "./autopilot";
export type { AutopilotMode, AutopilotPolicy, AutopilotDecision, AutopilotModeCopy } from "./autopilot";
export { buildMultiCloudSummary } from "./multiCloudSummary";
export type { MultiCloudSummary, ProviderRunInput } from "./multiCloudSummary";
export { prioritizeMultiCloudRecommendations, runPrioritizerTests, SCORING_RULES } from "./multiCloudPrioritizer";
export type { PrioritizedRecommendation, MultiCloudRecommendationInput, ScoreBreakdown } from "./multiCloudPrioritizer";
export { runReasoningEngine, runReasoningTests, PROMPT_TEMPLATES } from "./reasoningEngine";
export type {
  ReasoningContext,
  PreviousRunSummary,
  Theme,
  ThemeTag,
  ThemeDisposition,
  Tradeoff,
  ReasonedOutput,
  TrendAnalysis,
} from "./reasoningEngine";
export {
  generateAgentPlan,
  buildDependencyGraph,
  topologicalSort,
  detectCycles,
  getReadyPhases,
  runPlanningTests,
  EXAMPLE_PLANS,
} from "./planningEngine";
export type {
  AgentPlan,
  PlanPhase,
  PlanStatus,
  PhaseStatus,
  RolloutArchetype,
  PhasingStrategy,
  PhaseType,
  PhaseImpact,
  PhasePrecondition,
  SuccessCriterion,
  RollbackTrigger,
  DependencyEdge,
  DependencyGraph,
  ApprovalCheckpoint,
  PlanImpact,
  PlanRollbackSummary,
  PlanGenerationInput,
} from "./planningEngine";
export {
  diffSnapshots,
  shouldSuppress,
  buildMonitorNotification,
  runMonitor,
  runMonitoringTests,
  ALL_RULES,
  DEFAULT_ALERT_POLICY,
} from "./monitoringAgent";
export type {
  AlertSeverity,
  AlertCategory,
  MonitorAlert,
  AlertDelta,
  SnapshotDelta,
  ResourceChange,
  FieldChange,
  ComputeDelta,
  StorageDelta,
  RegionDelta,
  CostDelta,
  FlagsDelta,
  DiffRule,
  MonitorContext,
  VerifiedItem,
  PreviousAlert,
  AlertPolicy,
  SnoozedRule,
  EscalationRule,
  SuppressionState,
  MonitorResult,
  SuppressedAlert,
  MonitorNotification,
  MonitoringTestResult,
} from "./monitoringAgent";
export {
  recordSignal,
  recordApproval,
  recordRejection,
  recordExport,
  getSignals,
  clearSignals,
  aggregateProfile,
  applyAdaptiveBehavior,
  adaptiveCategoryBoost,
  inferRiskTolerance,
  inferOutputPreference,
  resetAdaptiveBehavior,
  inspectAdaptiveBehavior,
  validateAdjustments,
  runAdaptiveTests,
  DEFAULT_ADAPTIVE_CONFIG,
} from "./adaptiveBehavior";
export type {
  SignalType,
  BehaviorSignal,
  BehaviorProfile,
  ActionTypeRate,
  CategoryRate,
  ProviderActivity,
  RiskApprovalDistribution,
  AdaptiveAdjustment,
  AdjustmentType,
  AdaptiveResult,
  AdaptiveConfig,
  RiskToleranceSuggestion,
  SafeguardCheck,
  AdaptiveTestResult,
} from "./adaptiveBehavior";
export {
  detectDrift,
  runDriftTests,
  ALL_DRIFT_RULES,
  DEFAULT_RESILIENCE_BASELINE,
} from "./driftEngine";
export type {
  DriftSeverity,
  DriftCategory,
  DriftSource,
  DriftItem,
  DriftFieldChange,
  DriftImpact,
  DriftRemediation,
  RemediationAction,
  DriftReport,
  DriftSummary,
  DriftNotification,
  DriftNotificationSection,
  TerraformPlanState,
  TerraformResourceState,
  ExecutionPlanState,
  ApprovedPlanItem,
  ResilienceBaseline,
  DriftRule,
  DriftEvalContext,
  DetectDriftInput,
  DriftTestResult,
} from "./driftEngine";
export {
  registerWorkflow,
  getWorkflow,
  listWorkflows,
  deleteWorkflow,
  enableWorkflow,
  disableWorkflow,
  getExecutionHistory,
  getOrgExecutionHistory,
  shouldTrigger,
  evaluateConditions,
  executeActions,
  executeWorkflow,
  fireEvent,
  runWorkflowTests,
  EXAMPLE_WORKFLOWS,
} from "./workflowEngine";
export type {
  Workflow,
  WorkflowTrigger,
  ScheduleTrigger,
  ScanCompletedTrigger,
  AlertFiredTrigger,
  ApprovalCompletedTrigger,
  ThresholdCrossedTrigger,
  ThresholdMetric,
  ManualTrigger,
  WorkflowCondition,
  FindingCountCondition,
  SavingsCondition,
  SeverityCondition,
  CategoryCondition,
  ProviderCondition,
  AlertCategoryCondition,
  RiskLevelCondition,
  TimeWindowCondition,
  WorkflowAction,
  RunScanAction,
  GeneratePlanAction,
  GenerateTerraformAction,
  GenerateCLIAction,
  SendNotificationAction,
  NotificationTemplate,
  ApplySafeFixesAction,
  CreateSummaryAction,
  TriggerContext,
  WorkflowMetrics,
  WorkflowExecution,
  ConditionResult,
  ActionResult,
  WorkflowTestResult,
} from "./workflowEngine";
export {
  hasPermission,
  getPermissions,
  isRoleAtLeast,
  canManageRole,
  isProviderInScope,
  authorize,
  resolveApprovalPolicy,
  resolveWithDefaults,
  createChain,
  getChain,
  getChainsForItem,
  getChainsForOrg,
  castVote,
  resolveChain,
  checkEscalation,
  logRbacEvent,
  getRbacAuditLog,
  authorizeAction,
  getPresetNames,
  loadPreset,
  runRbacTests,
  EXAMPLE_POLICIES,
  POLICY_PRESETS,
} from "./rbacEngine";
export type {
  Permission,
  Membership,
  AuthorizationResult,
  ApprovalPolicyDef,
  ApprovalTarget,
  PolicyMatch,
  ApprovalChain,
  ApprovalVote,
  VoteDecision,
  VoteInput,
  VoteResult,
  ChainResolution,
  EscalationCheck,
  RbacAuditEvent,
  RbacAuditAction,
  AuthorizationDecision,
  PolicyPreset,
  RbacTestResult,
} from "./rbacEngine";
export {
  generateCorrelationId,
  setLogLevel,
  addLogSink,
  removeAllSinks,
  addMetricSink,
  removeAllMetricSinks,
  log,
  getLogBuffer,
  clearLogBuffer,
  incCounter,
  setGauge,
  recordHistogram,
  getCounter,
  getGauge,
  getHistogram,
  getHistogramStats,
  resetMetrics,
  registerAlertRule,
  removeAlertRule,
  listAlertRules,
  getFiredAlerts,
  evaluateAlertRules,
  getHealthCheck,
  exportMetrics,
  logRunStarted,
  logRunCompleted,
  logRunFailed,
  logConnectorAuth,
  logConnectorFetch,
  logSnapshotQuality,
  logTerraformGenerated,
  logTerraformFailed,
  logApplyStarted,
  logApplySuccess,
  logApplyFailed,
  logRollback,
  logVerification,
  logNotification,
  logWorkflow,
  logMonitorAlert,
  runObservabilityTests,
  DASHBOARDS,
  DEFAULT_ALERT_RULES,
} from "./observability";
export type {
  CorrelationContext,
  LogLevel,
  LogCategory,
  StructuredLogEntry,
  MetricType,
  MetricName,
  MetricTags,
  HistogramStats,
  AlertSeverityLevel,
  AlertRule,
  AlertCondition,
  AlertChannel,
  FiredAlert,
  HealthStatus,
  HealthCheck,
  ComponentHealth,
  DashboardPanel,
  Dashboard,
  MetricsSnapshot,
  ObservabilityTestResult,
} from "./observability";
export {
  evaluateGovernance,
  validatePolicy,
  toApprovalContext,
  filterByEnforcement,
  groupByDomain,
  getPresetPolicies,
  runGovernanceTests,
  SAMPLE_POLICIES,
  POLICY_PRESETS as GOVERNANCE_PRESETS,
} from "./governanceEngine";
export type {
  PolicyDomain,
  PolicySeverity,
  PolicyEnforcement,
  PolicyScope,
  GovernancePolicy,
  PolicyRule,
  NoPublicStorageRule,
  RequireReplicationRule,
  RequireMultiRegionRule,
  RequireBackupsRule,
  MaxMonthlyCostRule,
  MaxIdleCpuRule,
  RequireTagsRule,
  MaxResourceCountRule,
  RequireEncryptionRule,
  MinStorageClassRule,
  PolicyViolation,
  ViolationEvidence,
  ViolationRemediation,
  PolicyRemediation,
  GovernanceReport,
  GovernanceSummary,
  GovernanceNotification,
  GovernanceNotificationSection,
  PolicyEvalContext,
  EvaluateGovernanceInput,
  GovernanceApprovalContext,
  PolicyValidationResult,
  PolicyPresetName,
  PolicyPreset as GovernancePolicyPreset,
  GovernanceTestResult,
} from "./governanceEngine";
export {
  explainFinding,
  explainRecommendation,
  explainGovernanceViolation,
  explainDriftItem,
  explainMonitorAlert,
  explainFindings,
  explainGovernanceViolations,
  explainDriftItems,
  computeConfidenceAssessment,
  buildMetricEvidence,
  buildStateEvidence,
  buildThresholdEvidence,
  buildFlagEvidence,
  buildAbsenceEvidence,
  buildHistoricalEvidence,
  toExplanationCard,
  validateExplanation,
  runExplainabilityTests,
} from "./explainabilityEngine";
export type {
  EvidenceType,
  EvidenceConfidence,
  EvidenceReference,
  Explanation,
  ExplanationSubject,
  Assumption,
  Risk,
  ConfidenceAssessment,
  ConfidenceLevel,
  ConfidenceFactor,
  ProviderContext,
  DataCompletenessInput,
  ExplanationCard,
  ExplanationSection,
  ExplanationValidation,
  ExplainabilityTestResult,
} from "./explainabilityEngine";
export {
  runCognitiveLoop,
  shouldEscalate,
  runCognitiveTests,
  DEFAULT_AUTONOMY,
  ARCHITECTURE_MAP,
  AUTONOMY_LADDER,
} from "./cognitiveArchitecture";
export type {
  WorkingMemory,
  AgentPhase,
  AgentError,
  AgentDecision,
  ConfidenceState,
  EpisodicMemory,
  Episode,
  PhaseOutcome,
  SemanticMemory,
  ResourcePattern,
  CostBaseline,
  OrgRiskProfile,
  ProviderPreference,
  OperationalRhythm,
  KnownException,
  AutonomyLevel,
  AutonomyConfig,
  EscalationPolicy,
  HumanCheckpoint,
  SafetyBounds,
  CognitiveLoopInput,
  CognitiveLoopResult,
  LoopSummary,
  ScheduledAction,
  HumanActionRequired,
  ExecutionOutcome,
  VerificationOutcome,
  ReflectionNote,
  ReflectionCategory,
  AutonomyLevelSpec,
  CognitiveTestResult,
} from "./cognitiveArchitecture";
export {
  queryMemory,
  recordEpisode,
  recordIncident,
  recordApproval as recordMemoryApproval,
  recordRollback,
  learnOptimizationPattern,
  recordStrategy,
  ageMemory,
  summarizeMemory,
  updateGrowthTrend,
  deriveDecisionCulture,
  createEmptyMemory,
  runMemoryTests,
  DEFAULT_AGING,
  DEFAULT_PROVIDER_MAPPINGS,
  PRISMA_SCHEMA_GUIDANCE,
} from "./memorySystem";
export type {
  MemoryProvenance,
  MemorySource,
  StalenessLevel,
  EpisodicStore,
  StoredEpisode,
  Incident,
  IncidentType,
  RollbackRecord,
  ApprovalRecord,
  ScanRecord,
  SemanticStore,
  InfraTopology,
  GrowthTrend,
  TrendPoint,
  ResilienceSnapshot,
  OptimizationPattern,
  ProviderMapping,
  ProceduralStore,
  ExecutionStrategy,
  StrategyCondition,
  StrategyStep,
  WorkflowTemplate,
  RollbackPlaybook,
  EscalationPattern,
  OrganizationalStore,
  OrgIdentity,
  DecisionCulture,
  CompliancePosture,
  TeamStructure,
  PreferenceEvolution,
  CustomPolicy,
  AgentMemory,
  MemoryQuery,
  MemoryFilter,
  MemoryQueryResult,
  MemoryMutation,
  AgingConfig,
  AgingResult,
  MemorySummary,
  EpisodeSummary,
  SemanticSummaryReport,
  ProceduralSummaryReport,
  OrgSummaryReport,
  MemoryTestResult,
} from "./memorySystem";
export {
  runReflection,
  applyReflectionFeedback,
  runReflectionTests,
} from "./reflectionEngine";
export type {
  ReflectionInput,
  ReflectionReport,
  ReflectionSummary,
  ReflectionGrade,
  ReflectionMetrics,
  ReflectionInsight,
  ReflectionDomain,
  InsightEvidence,
  ReflectionAdjustment,
  AdjustmentType as ReflectionAdjustmentType,
  CalibrationReport,
  CalibrationBucket,
  NoiseAnalysis,
  NoisyCategory,
  NoisyProvider,
  SuppressionSuggestion,
  AdoptionAnalysis,
  CategoryAdoption,
  ProviderAdoption,
  RiskAdoption,
  SafetyReview,
  RollbackDetail,
  FeedbackApplication,
  ReflectionTestResult,
} from "./reflectionEngine";
export {
  createOperation,
  getReadySteps,
  advanceOperation,
  approveStep,
  startStep,
  completeStep,
  verifyStep,
  rollbackStep,
  cancelOperation,
  pauseOperation,
  resumeOperation,
  buildOperationSummary,
  detectDependencyCycles,
  getExecutionOrder,
  validateOperation,
  runOrchestratorTests,
  OPERATION_TEMPLATES,
} from "./operationOrchestrator";
export type {
  OperationType,
  OperationStatus,
  StepStatus,
  Operation,
  OperationStep,
  StepDependency,
  DependencyType,
  DependencyCondition,
  OperationRisk,
  RiskFactor,
  RiskMitigation,
  RiskSimulation,
  SimulationScenario,
  SimulationOutcome,
  BlastRadius,
  ApprovalCheckpoint as OperationCheckpoint,
  CheckpointApproval,
  StepPrecondition,
  PreconditionCheck,
  VerificationCriterion,
  VerificationResult,
  CriterionResult,
  ExecutionResult,
  ExecutionError,
  ProviderResponse,
  RollbackStrategy,
  RollbackProcedure,
  RollbackAction,
  RollbackResult,
  CanaryConfig,
  CanaryMetric,
  OperationSchedule,
  MaintenanceWindow,
  CostImpact,
  AuditEntry,
  AuditAction,
  OperationMetrics,
  CreateOperationInput,
  ResourceTarget,
  OperationAdvanceResult,
  AdvanceAction,
  OperationSummary,
  OperationValidation,
  OrchestratorTestResult,
} from "./operationOrchestrator";
export {
  registerTool,
  unregisterTool,
  getTool,
  listTools,
  getToolCount,
  clearRegistry,
  registerVerifier,
  verifyOutput,
  invokeTool,
  selectTool,
  executePipeline,
  getTraces,
  clearTraces,
  analyzeTraces,
  registerBuiltinTools,
  runToolFrameworkTests,
  BUILTIN_TOOLS,
} from "./toolFramework";
export type {
  ToolCategory,
  ToolCapability,
  ToolRiskLevel,
  ToolId,
  ToolDefinition,
  ToolParamSchema,
  ParamDefinition,
  ToolPrecondition,
  ToolHandler,
  ToolFilter,
  ToolContext,
  ToolAuthorization,
  ToolInput,
  ToolOutput,
  ToolOutputMetadata,
  ToolError,
  ExecutionTrace,
  TraceFilter,
  ValidationResult as ToolValidationResult,
  PreconditionResult,
  RetryPolicy,
  InvocationResult,
  ToolSelectionInput,
  ToolSelection,
  ToolPipelineStep,
  ToolPipeline,
  PipelineResult,
  PipelineStepResult,
  OutputVerifier,
  VerificationOutcome as ToolVerificationOutcome,
  TraceAnalysis,
  ToolFrameworkTestResult,
} from "./toolFramework";
export {
  evaluate as evaluateWorkflowIntelligence,
  reviewAdaptation,
  activateAdaptation,
  freezeAdaptation,
  rollbackAdaptation,
  recordAdaptationMetric,
  runWorkflowIntelligenceTests,
} from "./workflowIntelligence";
export type {
  LearningDimension,
  DimensionWeight,
  WorkflowObservation,
  ObservationSignal,
  PrioritySignal,
  SequencingSignal,
  NoiseSignal,
  RiskSignal,
  SavingsSignal,
  ApprovalSignal,
  ExecutionSignal,
  LearnedPattern,
  PatternType,
  PatternEvidence,
  Adaptation,
  AdaptationRule,
  AdaptationStatus,
  AdaptationGovernance,
  GovernanceEntry,
  AdaptationMetrics,
  EvaluationInput,
  EvaluationReport,
  DimensionScore,
  Regression,
  SafeguardResult as IntelligenceSafeguardResult,
  IntelligenceRecommendation,
  EvaluationSummary,
  WorkflowIntelligenceTestResult,
} from "./workflowIntelligence";
export {
  getRoadmapByPhase,
  getRoadmapByCategory,
  getRoadmapProgress,
  getBlockingBottlenecks,
  getMilestoneById,
  getDependencyChain,
  runRoadmapTests,
  FULL_ROADMAP,
  NEVER_FULLY_AUTONOMOUS,
  BOTTLENECKS,
  CAPABILITY_MATRIX,
} from "./roadmap";
export type {
  RoadmapPhase,
  MilestoneStatus,
  MilestoneCategory,
  Milestone,
  AutonomyGate,
  SuccessMetric,
  BottleneckCategory,
  Bottleneck,
  NeverAutomate,
  CapabilityLevel,
  CapabilityProgression,
  RoadmapTestResult,
} from "./roadmap";
export {
  getSubsystemsByLayer,
  getSubsystemsByStatus,
  getSubsystemById,
  getCriticalSubsystems,
  getSubsystemGaps,
  getArchitectureCompleteness,
  getAWSCompletionProgress,
  getMVPReadiness,
  getOpenRisks,
  getCriticalRisks,
  runArchitectureTests,
  SUBSYSTEMS,
  AWS_COMPLETION_ROADMAP,
  BUILD_PHASES,
  TECHNICAL_RISKS,
  PRODUCT_RISKS,
  DEFENSIBILITY,
  MVP_REQUIREMENTS,
  DEFERRED_ITEMS,
  ENTERPRISE_TRUST_FACTORS,
  ARCHITECTURE_DIAGRAMS,
} from "./platformArchitecture";
export type {
  SystemLayer,
  SubsystemStatus,
  SubsystemPriority,
  Subsystem,
  ArchitectureDiagram,
  BuildPhase,
  TechnicalRisk,
  ProductRisk,
  DefensibilityFactor,
  MVPRequirement,
  DeferredItem,
  TrustFactor,
  AWSCompletionItem,
  ArchitectureTestResult,
} from "./platformArchitecture";
export {
  getProviderCapabilities,
  getProviderGaps,
  getProviderParity,
  getAzureRoadmapByPhase,
  getGCPRoadmapByPhase,
  getResourceMapping,
  getMultiCloudEstimate,
  runMultiCloudTests,
  CAPABILITY_MATRIX as PROVIDER_CAPABILITY_MATRIX,
  RESOURCE_MAPPINGS,
  ABSTRACTION_COMPONENTS,
  SHARED_INTERFACES,
  AZURE_ROADMAP,
  GCP_ROADMAP,
  MULTI_CLOUD_ANTI_PATTERNS,
  CROSS_CLOUD_CAPABILITIES,
} from "./multiCloudStrategy";
export type {
  CloudProvider as AxiomCloudProvider,
  ProviderCapability,
  CapabilityStatus,
  ProviderCapabilityMatrix,
  ResourceCategory,
  ResourceMapping,
  AdapterRoadmapItem,
  AbstractionLayerComponent,
  SharedInterface,
  InterfaceMethod,
  AntiPattern,
  CrossCloudCapability,
  MultiCloudTestResult,
} from "./multiCloudStrategy";
export {
  computeTrustScore,
  getSecurityControlsByType,
  getActiveSecurityControls,
  getCriticalThreats,
  getComplianceReadiness,
  getInvariantCoverage,
  getTrustLevelRequirements,
  runTrustModelTests,
  TRUST_LADDER,
  SECURITY_LAYERS,
  THREAT_MODEL,
  COMPLIANCE_FRAMEWORKS,
  CREDENTIAL_POLICIES,
  SAFETY_INVARIANTS,
  ONBOARDING_JOURNEY,
} from "./enterpriseTrustModel";
export type {
  TrustLevel,
  TrustDimension,
  TrustScore,
  TrustEvent,
  TrustRequirement,
  PromotionRequirement,
  SecurityLayer,
  SecurityControl,
  ThreatModel as ThreatModelEntry,
  ComplianceFramework as AxiomComplianceFramework,
  ComplianceRequirement,
  CredentialPolicy,
  SafetyInvariant,
  OnboardingStep,
  TrustModelTestResult,
} from "./enterpriseTrustModel";
export {
  getPhaseDefinition,
  getPhaseOrder,
  getTransitionsFrom,
  getHumanGates,
  getRecoveryStrategy,
  getCriticalRecoveries,
  getSubsystemsForPhase,
  getQualityTargets,
  getImplementationByPhase,
  getImplementationProgress,
  runCognitiveCoreTests,
  PHASE_DEFINITIONS,
  PHASE_TRANSITIONS,
  CONTEXT_LAYERS,
  MEMORY_INFLUENCES,
  EXPLAINABILITY_CONTRACT,
  AUTONOMY_BOUNDARIES,
  COORDINATION_MAP,
  MULTI_CLOUD_COGNITION,
  CONFIDENCE_MODEL,
  RECOVERY_STRATEGIES,
  QUALITY_DIMENSIONS,
  LIFECYCLE_DIAGRAMS,
  IMPLEMENTATION_ROADMAP,
} from "./cognitiveCore";
export type {
  CognitivePhase,
  PhaseTransition,
  TransitionCondition,
  PhaseDefinition,
  ContextType,
  ContextLayer,
  MemoryInfluence,
  ExplainabilityRequirement,
  AutonomyBoundary,
  SubsystemCoordination,
  MultiCloudCognition,
  ConfidenceDimension,
  FailureCategory,
  RecoveryStrategy,
  QualityDimension,
  LifecycleDiagram,
  ImplementationStep,
  CognitiveCoreTestResult,
} from "./cognitiveCore";
export {
  createEmptyGraph,
  addNode,
  addEdge,
  getNeighbors,
  traverseBFS,
  getNodesByKind,
  getNodesByProvider,
  getEdgesByKind,
  computeStaleness as computeGraphStaleness,
  getAgingPolicy,
  getRetrievalIntents,
  validateEdgeSchema,
  getGraphStats,
  getGovernanceViolations,
  runMemoryGraphTests,
  EDGE_SCHEMAS,
  AGING_POLICIES,
  DEFAULT_COMPACTION,
  RETRIEVAL_FLOW,
  SUMMARIZATION_RULES,
  GOVERNANCE_RULES,
  GRAPH_DIAGRAMS,
  PRISMA_GRAPH_GUIDANCE,
} from "./operationalMemoryGraph";
export type {
  GraphNodeKind,
  GraphNode,
  GraphProvider,
  GraphStaleness,
  GraphEdgeKind,
  GraphEdge,
  EdgeSchema,
  MemoryGraph,
  GraphStats,
  GraphQuery,
  TraversalStrategy,
  GraphQueryResult,
  GraphPath,
  RetrievalRequest,
  RetrievalIntent,
  RetrievalContext,
  RetrievalConstraints,
  RetrievalResult,
  SummarizationStrategy,
  SummarizationRule,
  SummarizationTrigger,
  SummarizationResult,
  AgingPolicy,
  CompactionConfig,
  CompactionResult,
  EvolutionEvent,
  EvolutionEventType,
  EvolutionImpact,
  EvolutionTimeline,
  EvolutionMilestone,
  PeriodSummary,
  GraphGovernanceRule,
  GraphDiagram,
  MemoryGraphTestResult,
} from "./operationalMemoryGraph";
export {
  createWorkflowInstance,
  startWorkflow,
  advanceWorkflow,
  completeStage,
  failStage,
  pauseWorkflow,
  resumeWorkflow,
  cancelWorkflow,
  approveGate,
  checkProviderCapability,
  checkSafetyBoundary,
  getRetryPolicy,
  getWorkflowTemplate,
  getStageDependencies,
  getWorkflowProgress,
  getAuditTrail,
  runAutonomousOrchestratorTests,
  DEFAULT_CHECKPOINT_POLICY,
  RETRY_POLICIES,
  DEFAULT_SAFETY_BOUNDARY,
  PROVIDER_CAPABILITIES,
  WORKFLOW_TEMPLATES,
  STAGE_DEPENDENCIES,
  DEFAULT_COORDINATION_POLICY,
  ORCHESTRATOR_DIAGRAMS,
} from "./autonomousOrchestrator";
export type {
  WorkflowInstanceStatus,
  WorkflowStage,
  StageStatus,
  WorkflowInstance,
  OrchestratorProvider,
  WorkflowTriggerSource,
  WorkflowTiming,
  StageExecution,
  StageInput,
  StageOutput,
  StageArtifact,
  ArtifactType,
  StageMetrics,
  StageError,
  StageErrorCode,
  WorkflowCheckpoint,
  CheckpointState,
  ProviderCheckpointState,
  CheckpointPolicy,
  WorkflowRetryState,
  RetryRecord,
  BackoffState,
  BackoffStrategy,
  RetryPolicy as OrchestratorRetryPolicy,
  ApprovalGateState,
  ApprovalVoteRecord,
  AutoApproveCondition,
  GateRiskAssessment,
  RollbackCoordinationState,
  RollbackTriggerCause,
  StageRollbackEntry,
  RollbackAction as OrchestratorRollbackAction,
  RollbackStrategyType,
  RollbackSafetyCheck,
  SafetyBoundary,
  FreezePeriod,
  ProviderBoundary,
  ProviderCapabilityResult,
  ProviderCapabilitySpec,
  PolicyCheckResult,
  PolicyViolationDetail,
  AuditTrail,
  AuditEntry as OrchestratorAuditEntry,
  AuditAction as OrchestratorAuditAction,
  AuditActor,
  WorkflowTemplate as OrchestratorWorkflowTemplate,
  StageDependency,
  TaskCoordinator,
  ProviderLock,
  ResourceLock,
  QueuedWorkflow,
  CoordinationPolicy,
  OrchestratorDiagram,
  WorkflowNextAction,
  OrchestratorTestResult as AutonomousOrchestratorTestResult,
} from "./autonomousOrchestrator";
export {
  evaluateGovernanceDecision,
  getTrustRequirementForAction,
  getAutonomyRequirementForAction,
  getPhaseGovernance,
  getTrustAutonomyMapping,
  getAllowedActionsForTrust,
  getComplianceControls,
  getApplicableInvariants,
  runGovernanceEngineTests,
  TRUST_REQUIREMENTS_PER_ACTION,
  AUTONOMY_REQUIREMENTS,
  PHASE_GOVERNANCE,
  TRUST_AUTONOMY_MAP,
  COMPLIANCE_CONTROL_MAP,
  POLICY_EXAMPLES,
  GOVERNANCE_DIAGRAMS,
  SAFETY_INVARIANTS as GOVERNANCE_SAFETY_INVARIANTS,
} from "./trustSafetyGovernance";
export type {
  GovernanceDecision,
  GovernanceVerdict,
  ActionRequest,
  GovernanceActionType,
  GovernanceProvider,
  GovernanceRiskLevel,
  ActionRequestor,
  CognitivePhaseRef,
  TrustEvaluation,
  TrustLevelRef,
  TrustEventSummary,
  AutonomyEvaluation,
  AutonomyRequirement,
  PolicyEvaluation,
  GovernancePolicyViolation,
  RBACEvaluation,
  SafetyEvaluation,
  SafetyInvariantCheck,
  ProviderEvaluation,
  RollbackEvaluation,
  EvidenceLink,
  EvidenceType as GovernanceEvidenceType,
  EscalationRequirement,
  EscalationReason,
  GovernanceCondition,
  PhaseGovernancePolicy,
  GovernanceCheckType,
  TrustAutonomyMapping,
  ComplianceEvidence,
  ComplianceEvidenceType,
  ComplianceSnapshot,
  ComplianceGap,
  GovernanceDrift,
  GovernanceDriftType,
  GovernancePolicyExample,
  GovernanceDiagram,
  GovernanceContext,
  GovernanceEngineTestResult,
} from "./trustSafetyGovernance";
export {
  getProviderProfile,
  getDomainDefinition,
  getResourceMappingForType,
  getResourceMappingsForDomain,
  getActionMapping,
  getActionsForDomain,
  getDomainCapability,
  getProviderDomainSummary,
  canProviderExecuteAction,
  getAbstractionCompleteness,
  runMultiCloudAbstractionTests,
  PROVIDER_PROFILES,
  DOMAIN_DEFINITIONS,
  RESOURCE_MAPPING_REGISTRY,
  ACTION_MAPPINGS,
  CAPABILITY_REGISTRY,
  ADAPTER_METHODS,
  COGNITIVE_ISOLATION_RULES,
  COST_NORMALIZATION,
  TRANSLATION_EXAMPLES,
} from "./multiCloudAbstraction";
export type {
  SupportedProvider,
  ProviderTier,
  ProviderProfile,
  AuthMethod,
  OperationalDomain,
  DomainDefinition,
  Subdomain,
  UnifiedResourceType,
  UnifiedResource,
  ComplianceFlag,
  ProviderResourceMapping,
  ProviderResourceSpec,
  CostDimension,
  UnifiedAction,
  ActionMapping,
  ActionRiskLevel,
  ProviderActionSpec,
  DomainCapabilityStatus,
  DomainCapabilityEntry,
  DomainCapabilityDetail,
  ProviderAdapterContract,
  AdapterCapability,
  AdapterMethod,
  CognitiveIsolationRule,
  CostNormalizationSpec,
  ProviderCostConversion,
  ProviderTranslationExample,
  AbstractionTestResult,
} from "./multiCloudAbstraction";
export {
  getIntelligenceStage,
  getIntelligenceStageOrder,
  getIntelligenceDependencies,
  getReadyIntelligenceStages,
  getIntegrationForSubsystem,
  getRoadmapByPhase as getIntelligenceRoadmapByPhase,
  getIntelligenceRoadmapProgress,
  getTopologyDiscoveryMethods,
  runInfrastructureIntelligenceTests,
  INTELLIGENCE_INTEGRATIONS,
  INTELLIGENCE_PIPELINE,
  INTELLIGENCE_ROADMAP,
  INTELLIGENCE_DIAGRAMS,
} from "./infrastructureIntelligence";
export type {
  TopologyNodeType,
  TopologyEdgeType,
  TopologyNode,
  TopologyHealthStatus,
  TopologyCriticality,
  TopologyEdge,
  TopologyDiscoveryMethod,
  BandwidthEstimate,
  InfrastructureTopologyMap,
  TopologyZone,
  TopologyZoneType,
  TopologyMapSummary,
  RelationshipStrength,
  InfraRelationship,
  FailureImpactLevel,
  RelationshipEvidence,
  DependencyChainAnalysis,
  DependencyChain,
  BlastRadiusAssessment,
  InfraFailureMode,
  UserImpactEstimate,
  WorkloadProfile,
  WorkloadType,
  WorkloadBehaviorPattern,
  WorkloadGrowthTrend,
  PeakSchedule,
  SeasonalPeak,
  QuietPeriod,
  UtilizationBaseline,
  WorkloadCostProfile,
  WorkloadResiliencePosture,
  InfraEvolutionCategory,
  InfraEvolutionTimeline,
  TimeRange,
  InfraStateSnapshot,
  InfraTransition,
  InfraTrend,
  TrendDataPoint,
  TrendForecast,
  TrendSignificance,
  InfraMilestone,
  MilestoneImpact,
  InfraRiskCategory,
  InfraRiskSeverity,
  InfraRiskSignal,
  RiskEvidence as IntelligenceRiskEvidence,
  TimeToImpactEstimate,
  RiskMitigation as IntelligenceRiskMitigation,
  RiskLandscape,
  OptimizationTrendReport,
  OptimizationTrend,
  RecurringOpportunity,
  UnrealizedSaving,
  StressIndicator,
  StressPattern,
  StressPatternShape,
  StressEscalation,
  StressForecast,
  PredictedIncident,
  CapacityBottleneck,
  ResilienceWeakness,
  ResilienceAssessment,
  ResilienceDomainScore,
  ResilienceWeaknessDetail,
  ResilienceComparison,
  ResilienceRecommendation,
  OrgInfraProfile,
  InfraMaturityLevel,
  ProviderStrategy,
  OperationalCadence,
  CostGovernancePosture,
  SecurityPostureSummary,
  ChangeVelocity,
  TeamCapabilityAssessment,
  IntelligenceIntegration,
  IntelligencePipelineStage,
  IntelligenceStageDefinition,
  IntelligenceReport,
  IntelligenceInsight,
  IntelligenceQuality,
  IntelligenceRoadmapPhase,
  IntelligenceRoadmapItem,
  IntelligenceDiagram,
  IntelligenceTestResult,
} from "./infrastructureIntelligence";
export {
  getSimulationPipelineStage,
  getSimulationPipelineOrder,
  getRiskWeight,
  getRiskCategory,
  getVerdict,
  computeCompositeRiskScore,
  getProviderSimulationFidelity,
  getProviderSimulationSummary,
  getApplicableAdjustments,
  runOperationalSimulationTests,
  RISK_WEIGHTS,
  RISK_THRESHOLDS,
  VERDICT_MAPPING,
  CONSERVATIVE_ADJUSTMENTS,
  DOWNTIME_PROBABILITY_THRESHOLDS,
  DOWNTIME_FACTORS,
  ROLLBACK_COMPLEXITY_FACTORS,
  SIMULATION_PIPELINE,
  SIMULATION_PRINCIPLES,
  PROVIDER_SIMULATION_CAPABILITIES,
} from "./operationalSimulation";
export type {
  SimulationMode,
  SimulationStatus,
  SimulationRequest,
  SimulationType,
  SimulationTarget,
  SimulationConstraints,
  SimulationContext,
  TopologyReference,
  RecentIncidentRef,
  ApprovalPatternRef,
  UtilizationRef,
  OperationalSimulationResult,
  SimulationVerdict,
  SimulationExplanation,
  SimulationEvidenceItem,
  SimulationWarning,
  SimulationQualityAssessment,
  CompositeRiskScore,
  RiskComponent,
  RiskAdjustment,
  RolloutRiskResult,
  RolloutPhaseRisk,
  RolloutGate,
  RolloutSequence,
  RolloutPhaseSpec,
  DowntimeLikelihoodResult,
  DowntimeEstimate,
  DowntimeServiceImpact,
  DowntimeMitigation,
  DowntimeFactor,
  RollbackComplexityResult,
  RollbackStrategySpec,
  RollbackStep,
  RollbackBlocker,
  StateCapturePlan,
  RegionFailureResult,
  RegionFailureScenario,
  RegionFailureImpact,
  SingleRegionRisk,
  ResilienceImprovementResult,
  ResilienceDimensionChange,
  CostSavingsResult,
  CostConfidenceRange,
  ResourceCostImpact,
  OneTimeCost,
  SavingsTimeline,
  DependencyConflictResult,
  ExecutionConflict,
  ExecutionConflictType,
  ConflictResolution,
  ScalingBehaviorResult,
  AutoScalingImpact,
  CapacityHeadroom,
  ScaleLatencyChange,
  ReplicationChangeResult,
  ReplicationChangeDetail,
  ReplicationState,
  DataConsistencyRisk,
  ReplicationLagImpact,
  DataTransferChange,
  SimPipelineStage,
  SimPipelineDefinition,
  SimulationPrinciple,
  ProviderSimulationCapability,
  SimulationTestResult,
} from "./operationalSimulation";
export {
  getOrgLearningStage,
  getOrgLearningStageOrder,
  getOrgIntegrationForSubsystem,
  getOrgIntegrationsByPhase,
  validateOrgAdaptation,
  getAdaptationBudgetStatus,
  computeOrgMaturity,
  runOrganizationalIntelligenceTests,
  ORG_ADAPTATION_INVARIANTS,
  ORG_INTELLIGENCE_INTEGRATIONS,
  ORG_LEARNING_PIPELINE,
} from "./organizationalIntelligence";
export type {
  OrgMemoryStore,
  OrgMemoryCategory,
  OrgMemoryObservation,
  ObservationSource,
  OrgSignalData,
  OperationalDna,
  OrgOperationalMaturity,
  ChangePhilosophy,
  CommunicationStyle,
  DecisionSpeed,
  AutomationComfort,
  OrgCloudStrategy,
  ComplianceOrientation,
  CostSensitivity,
  ApprovalBehaviorModel,
  ApprovalCategoryRate,
  ApprovalRiskLevelRate,
  ApprovalTemporalPattern,
  ApproverProfile,
  RejectionReasonFrequency,
  EscalationPattern as OrgEscalationPattern,
  OrgRiskPosture,
  RiskToleranceLevel,
  DomainRiskTolerance,
  AcceptedRiskPattern,
  RiskEscalationThreshold,
  IncidentResponsePattern,
  RiskBudget,
  GrowthIntelligenceModel,
  ResourceGrowthPattern,
  CostGrowthPattern,
  CostGrowthDriver,
  RegionalExpansionPattern,
  ServiceAdoptionPattern,
  GrowthProjection,
  CloudUsagePatternModel,
  OrgUtilizationProfile,
  SchedulingPattern,
  ResourceLifecyclePattern,
  TagCompliancePattern,
  CostAllocationPattern,
  OptimizationPriorityModel,
  OptimizationFocus,
  DomainOptimizationPriority,
  AcceptedRecommendationPattern,
  RejectedRecommendationPattern,
  ImplementationVelocity,
  ExecutionTendencyModel,
  ExecutionPreferenceSet,
  ExecutionFailurePattern,
  RecoveryBehaviorProfile,
  VerificationHabits,
  WorkflowEfficiencyModel,
  StageBottleneck,
  ApprovalBottleneck,
  HandoffDelay,
  ThroughputMetrics,
  WastedEffortAnalysis,
  GovernanceLearningModel,
  ObservedGovernancePolicy,
  DetectedComplianceFramework,
  GovernanceEnforcementStyle,
  PolicyViolationPattern,
  AuditReadinessAssessment,
  OrgAdaptationState,
  OrgBehavioralAdaptation,
  OrgAdaptationEvidence,
  OrgAdaptationEffect,
  OrgAdaptationConstraint,
  OrgAdaptationBudget,
  OrgAdaptationInvariant,
  TransparencyLogEntry,
  TransparencyEventType,
  OrgControlPanel,
  OperationalDnaSummary,
  OrgOverride,
  OrgOverrideType,
  OrgIntelligenceIntegration,
  OrgLearningStage,
  OrgLearningStageDefinition,
  OrgIntelligenceTestResult,
} from "./organizationalIntelligence";

// ─────────────────────────────────────────────────────────────────────────────
// Autonomous Coordination Framework
// Multi-workflow orchestration with safety, isolation, and auditability
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Coordination Architecture
  type CoordinatedOperationType,
  type OperationPriority,
  type OperationIsolationLevel,
  type CoordinatedOperation,
  type ResourceClaim,
  type ApprovalDependency,

  // §2 — Operation State Machine
  type OperationStateMachineState,
  type OperationStateTransition,
  type TransitionTrigger,
  OPERATION_STATE_TRANSITIONS,

  // §3 — Concurrency Strategy
  type ConcurrencyPolicy,
  type FairnessPolicy,
  DEFAULT_CONCURRENCY_POLICY,
  type OperationSlot,
  type ConcurrencySnapshot,

  // §4 — Conflict Detection
  type ConflictCategory,
  type OperationConflict,
  type ConflictResolutionStrategy,
  type ConflictResolutionMethod,
  type ConflictDetectionRule,
  CONFLICT_DETECTION_RULES,

  // §5 — Scheduling & Priority
  type OperationScheduler,
  type ScheduledOperation,
  type ScheduleTarget,
  type SchedulePrecondition,
  type RecurringSchedule,
  type MaintenanceWindow as CoordinationMaintenanceWindow,
  type BlackoutPeriod,
  type PriorityCalculation,
  PRIORITY_SCORES,
  OPERATION_DEFAULT_PRIORITIES,
  OPERATION_ISOLATION_DEFAULTS,

  // §6 — Interruption & Resumption
  type InterruptionRequest,
  type InterruptionReason,
  type ResumptionRequest,
  type OperationCheckpointData,
  type ResumptionValidation,

  // §7 — Rollback Coordination
  type CoordinatedRollbackRequest,
  type CoordinatedRollbackReason,
  type CoordinatedRollbackStrategy,
  type CascadePolicy,
  type RollbackSafetyValidation,
  type CoordinatedRollbackPlan,
  type RollbackPhase,

  // §8 — Dependency Graph
  type OperationDependencyGraph,
  type OperationDependencyNode,
  type OperationDependencyEdge,
  type OperationDependencyType,

  // §9 — Recovery Strategy
  type RecoveryScenario,
  type RecoveryPlaybook,
  type RecoveryStep,
  RECOVERY_PLAYBOOKS,

  // §10 — Provider Coordination
  type ProviderCoordinationProfile,
  PROVIDER_COORDINATION_PROFILES,

  // §11 — Audit Trail
  type CoordinationAuditAction,
  type CoordinationAuditEntry,

  // §12 — Query Functions
  getOperationDefaultPriority,
  getOperationIsolationDefault,
  getConflictDetectionRule,
  getAutoResolvableConflicts,
  getRecoveryPlaybook,
  getAutomaticRecoveryPlaybooks,
  getCriticalRecoveryPlaybooks,
  getProviderCoordinationProfile,
  computeEffectivePriority,
  getValidTransitions,
  canTransition,
  isTerminalState,
  isActiveState,
  isWaitingState,

  // §13 — Tests
  type CoordinationTestResult,
  runAutonomousCoordinationTests,
} from "./autonomousCoordination";

// ─────────────────────────────────────────────────────────────────────────────
// Terraform Generation Engine
// Translates execution plans into safe, reviewable infrastructure-as-code
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Generation Architecture
  type IaCBackend,
  type GenerationMode,
  type ChangeAction,
  type ResourceLifecycleAction,
  type TerraformGenerationContext,
  type StateBackendConfig,
  type VariableSourceConfig,

  // §2 — Infrastructure Change Model
  type InfrastructureChangeSet,
  type ChangeSetStatus,
  type ResourceChange as TerraformResourceChange,
  type AttributeChange,
  type ChangeDependency,
  type DurationEstimate,

  // §3 — Blast Radius Computation
  type BlastRadiusSeverity,
  type BlastRadiusThreshold,
  type ChangeBlastRadius,
  type ComputedBlastRadius,
  type DownstreamImpact,
  type CostImpact as TerraformCostImpact,
  type DataLossRisk,
  type ThresholdViolation,
  type BlastRadiusRiskFactor,
  BLAST_RADIUS_WEIGHTS,
  BLAST_RADIUS_THRESHOLDS,
  computeBlastRadiusSeverity,

  // §4 — Terraform HCL Builder
  type HCLBlockType,
  type HCLBlock,
  type HCLAttribute,
  type HCLValue,
  type HCLNestedBlock,
  type HCLLifecycle,
  type TerraformModule,
  type TerraformVariable,
  type VariableValidation,
  type TerraformOutput,
  type RequiredProvider,

  // §5 — Generation Templates
  type TemplateCategory,
  type GenerationTemplate,
  type TemplateParameter,
  type TemplateSafetyCheck,
  GENERATION_TEMPLATES,

  // §6 — Generation Constraints & Safety
  type ConstraintSeverity,
  type GenerationConstraint,
  type ConstraintScope,
  type ConstraintCondition,
  type TimeWindow,
  SAFETY_CONSTRAINTS,

  // §7 — Rollback Plan Generation
  type RollbackStrategy as TerraformRollbackStrategy,
  type RollbackPlan,
  type RollbackStep as TerraformRollbackStep,
  type RollbackAction as TerraformRollbackAction,
  type RollbackTrigger as TerraformRollbackTrigger,
  type RollbackPreCheck,
  type StateSnapshotRef,
  type ResourceSnapshotRef,

  // §8 — Dry-Run & Validation
  type ValidationSeverity,
  type ChangeSetValidation,
  type DryRunResult,
  type TerraformPlanSummary,
  type ConstraintViolationResult,
  type ValidatorId,
  type ValidationPipeline,
  type ValidatorDefinition,
  VALIDATION_PIPELINE,

  // §9 — Governance Approval State
  type GovernanceApprovalStatus,
  type GovernanceApprovalState,
  type ApproverRequirement,
  type ApprovalRecord as TerraformApprovalRecord,
  type RejectionRecord,

  // §10 — Provider-Specific Generation Profiles
  type ProviderGenerationProfile,
  type NamingConvention,
  type ProviderStateManagement,
  type ProviderRateLimits,
  PROVIDER_GENERATION_PROFILES,

  // §11 — Generation Pipeline
  type GenerationStageId,
  type GenerationStageDefinition,
  GENERATION_PIPELINE,

  // §12 — Security Anti-Pattern Detection
  type SecurityAntiPatternId,
  type SecurityAntiPattern,
  SECURITY_ANTI_PATTERNS,

  // §13 — Integration Contracts
  type TerraformIntegrationTarget,
  type TerraformIntegrationContract,
  TERRAFORM_INTEGRATION_CONTRACTS,

  // §14 — Query Functions
  getGenerationTemplate,
  getTemplatesByCategory,
  getTemplatesByProvider,
  getTemplateForAction,
  getSafetyConstraint,
  getBlockingConstraints,
  getAbsoluteConstraints,
  getSecurityAntiPattern,
  getCriticalAntiPatterns,
  getAntiPatternsByCompliance,
  getProviderGenerationProfile,
  getGenerationPipelineStage,
  getGenerationPipelineOrder,
  getValidatorDefinition,
  getRequiredValidators,
  getTerraformIntegration,
  mapUnifiedResourceToProvider,

  // §15 — Tests
  type TerraformGenerationTestResult,
  runTerraformGenerationTests,
} from "./terraformGeneration";

// ─────────────────────────────────────────────────────────────────────────────
// Execution Safety Engine
// Safe infrastructure apply with pre-checks, progressive rollout, auto-rollback
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Execution Architecture
  type ExecutionStrategy as SafetyExecutionStrategy,
  type ExecutionPhase,
  type ExecutionOutcome as SafetyExecutionOutcome,
  type ExecutionContext,
  type AutonomyLevel as SafetyAutonomyLevel,
  AUTONOMY_LEVEL_PERMISSIONS,
  type AutonomyPermissions,

  // §2 — Pre-Execution Checks
  type PreCheckId,
  type PreExecutionCheck,
  type PreCheckResult,
  PRE_EXECUTION_CHECKS,

  // §3 — Safety Configuration
  type SafetyConfig,
  DEFAULT_SAFETY_CONFIG,
  CONSERVATIVE_SAFETY_CONFIG,

  // §4 — Health Check Framework
  type HealthCheckType,
  type HealthCheckConfig,
  type HealthCheckDefinition,
  type HealthCheckTarget,
  type ExpectedHealthState,
  type HealthCheckResult,
  type HealthBaseline,
  type BaselineMetric,
  DEFAULT_HEALTH_CONFIG,

  // §5 — Auto-Rollback Configuration
  type AutoRollbackTrigger,
  type AutoRollbackConfig,
  type AutoRollbackTriggerConfig,
  DEFAULT_ROLLBACK_CONFIG,

  // §6 — Circuit Breaker
  type CircuitBreakerState,
  type CircuitBreaker,
  type CircuitBreakerEvent,
  computeCircuitBreakerState,

  // §7 — Execution Progress Tracking
  type ExecutionProgress,
  type ExecutionStepProgress,
  type ExecutionStepStatus,
  type ExecutionStepError,

  // §8 — Progressive Rollout
  type CanaryConfig as ExecutionCanaryConfig,
  type BlueGreenConfig,
  type RollingConfig,
  type PromotionCriterion,
  DEFAULT_CANARY_CONFIG,
  DEFAULT_BLUE_GREEN_CONFIG,
  DEFAULT_ROLLING_CONFIG,

  // §9 — Kill Switch
  type KillSwitchScope,
  type KillSwitch,
  type KillSwitchPolicy,
  DEFAULT_KILL_SWITCH_POLICY,

  // §10 — Execution Audit Trail
  type ExecutionAuditAction,
  type ExecutionAuditEntry,

  // §11 — Provider Execution Profiles
  type ProviderExecutionProfile,
  type ApplyMechanism,
  type ProviderRollbackCapability,
  PROVIDER_EXECUTION_PROFILES,

  // §12 — Execution Invariants
  type ExecutionInvariant,
  EXECUTION_INVARIANTS,

  // §13 — Integration Contracts
  type ExecutionIntegrationTarget,
  type ExecutionIntegrationContract,
  EXECUTION_INTEGRATION_CONTRACTS,

  // §14 — Query Functions
  getPreExecutionCheck,
  getRequiredPreChecks,
  getPreChecksForStrategy,
  getAutonomyPermissions,
  canAutonomouslyApply,
  getProviderExecutionProfile,
  getTypicalApplyLatency,
  getRollbackCapability,
  isStrategySupported,
  getExecutionInvariant,
  getNonOverridableInvariants,
  getExecutionIntegration,
  estimateTotalApplyDuration,

  // §15 — Tests
  type ExecutionSafetyTestResult,
  runExecutionSafetyTests,
} from "./executionSafety";

// ─────────────────────────────────────────────────────────────────────────────
// Signal Detection & Processing Pipeline
// Unified operational signal intake feeding the cognitive reasoning loop
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Signal Architecture
  type SignalDomain,
  type SignalSeverity,
  type SignalConfidence,
  type SignalSource,
  type OperationalSignal,
  type SignalState,
  type SignalEvidence,
  type SignalProcessingEvent,

  // §2 — Signal Detection Rules
  type DetectionRuleType,
  type DetectionRule,
  type DetectionCondition,
  DETECTION_RULES,

  // §3 — Signal Enrichment
  type EnrichmentType,
  type EnrichmentResult,
  type EnrichmentPipeline,
  type EnrichmentStage,
  ENRICHMENT_PIPELINE,

  // §4 — Signal Correlation
  type CorrelationStrategy,
  type CorrelationRule,
  type CorrelationGroup,
  CORRELATION_RULES,

  // §5 — Signal Triage & Routing
  type TriageDisposition,
  type TriagePolicy,
  type TriageCondition,
  type RoutingDecision,
  type RoutingTarget,
  TRIAGE_POLICIES,

  // §6 — Signal Processing Pipeline
  type SignalPipelineStageId,
  type SignalPipelineStage,
  SIGNAL_PIPELINE,

  // §7 — Signal Suppression
  type SuppressionRule,
  type SuppressionDuration,

  // §8 — Signal Metrics & Analytics
  type SignalAnalytics,

  // §9 — Integration Contracts
  type SignalIntegrationTarget,
  type SignalIntegrationContract,
  SIGNAL_INTEGRATION_CONTRACTS,

  // §10 — Query Functions
  getDetectionRule,
  getDetectionRulesByDomain,
  getDetectionRulesByProvider,
  getEnabledDetectionRules,
  getCriticalDetectionRules,
  getTriagePolicy,
  getTriagePoliciesByDisposition,
  getAutoRemediablePolicies,
  getCorrelationRule,
  getCorrelationRulesByStrategy,
  getEnrichmentStage,
  getSignalPipelineStage,
  getSignalPipelineOrder,
  getSignalIntegration,
  computeSignalPriority,

  // §11 — Tests
  type SignalDetectionTestResult,
  runSignalDetectionTests,
} from "./signalDetection";

// ─────────────────────────────────────────────────────────────────────────────
// Incident Response Engine
// Automated incident lifecycle: detect → contain → remediate → verify → learn
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Incident Architecture
  type IncidentSeverityLevel,
  type IncidentCategory,
  type IncidentPhase,
  type Incident as IncidentRecord,
  type AffectedResource,
  type ImpactAssessment,
  type UserImpactLevel,
  type ServiceImpactLevel,
  type DataImpactLevel,
  type FinancialImpactEstimate,
  type IncidentBlastRadius,

  // §2 — Incident Classification
  type ClassificationRule,
  type ClassificationCondition,
  CLASSIFICATION_RULES,

  // §3 — Severity Definitions & SLA
  type SeverityDefinition,
  SEVERITY_DEFINITIONS,

  // §4 — Containment Strategies
  type ContainmentStrategy,
  type ContainmentAction,
  type ContainmentPlaybook,
  type ContainmentStep,
  CONTAINMENT_PLAYBOOKS,

  // §5 — Remediation Plans
  type RemediationPlan,
  type RemediationStrategy,
  type RemediationStatus,
  type RemediationStep,

  // §6 — Incident Timeline
  type IncidentTimelineEventType,
  type IncidentTimelineEntry,

  // §7 — Assignment & Escalation
  type IncidentAssignment,
  type EscalationPolicy as IncidentEscalationPolicy,
  type EscalationLevel,
  DEFAULT_ESCALATION_POLICY,

  // §8 — Verification & Recovery
  type VerificationCheck,
  type RecoveryValidation,

  // §9 — Post-Incident Review
  type PostIncidentReview,
  type RootCauseAnalysis,
  type PostIncidentActionItem,
  type LessonLearned,
  type PreventionRecommendation,

  // §10 — Incident Response Pipeline
  type IncidentPipelineStageId,
  type IncidentPipelineStage,
  INCIDENT_PIPELINE,

  // §11 — Incident Invariants
  type IncidentInvariant,
  INCIDENT_INVARIANTS,

  // §12 — Integration Contracts
  type IncidentIntegrationTarget,
  type IncidentIntegrationContract,
  INCIDENT_INTEGRATION_CONTRACTS,

  // §13 — Query Functions
  getSeverityDefinition,
  getClassificationRule,
  getAutoClassifiableRules,
  getClassificationRulesBySeverity,
  getContainmentPlaybook,
  getPlaybooksForCategory,
  getAutonomousPlaybooks,
  getIncidentPipelineStage,
  getIncidentPipelineOrder,
  getIncidentInvariant,
  getBlockingInvariants,
  canAutonomouslyRemediate,
  getResponseSla,
  getIncidentIntegration,

  // §14 — Tests
  type IncidentResponseTestResult,
  runIncidentResponseTests,
} from "./incidentResponse";

// ─────────────────────────────────────────────────────────────────────────────
// Cost Intelligence Engine
// Deep cost analysis, forecasting, optimization, and FinOps governance
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Cost Architecture
  type CostGranularity,
  type CostDimension as CostAnalysisDimension,
  type CostTrendDirection,
  type CostSnapshot,
  type CostBreakdownEntry,
  type MultiCloudCostSummary,
  type BudgetStatus,

  // §2 — Cost Anomaly Detection
  type AnomalyType,
  type CostAnomaly,
  type AnomalyDetectionConfig,
  type AnomalySuppressionRule,
  DEFAULT_ANOMALY_CONFIG,

  // §3 — Cost Optimization
  type OptimizationCategory,
  type OptimizationRisk,
  type CostOptimizationRecommendation,
  type OptimizationStatus,
  type OptimizationRule,
  type OptimizationCondition,
  type SavingsEstimationMethod,
  OPTIMIZATION_RULES,

  // §4 — Cost Forecasting
  type ForecastModel,
  type CostForecast,
  type ForecastDataPoint,
  type ConfidenceInterval,
  type ForecastAccuracy,

  // §5 — FinOps Governance
  type CostPolicy,
  type CostPolicyType,
  type CostPolicyScope,
  type CostPolicyThreshold,
  type CostPolicyAction,
  DEFAULT_COST_POLICIES,

  // §6 — Cost Attribution & Showback
  type CostAttributionModel,
  type SharedCostAllocationMethod,
  type CostShowbackReport,
  type TeamCostReport,

  // §7 — Provider Cost APIs
  type ProviderCostProfile,
  type TagRequirement,
  PROVIDER_COST_PROFILES,

  // §8 — Cost Intelligence Pipeline
  type CostPipelineStageId,
  type CostPipelineStage,
  COST_PIPELINE,

  // §9 — Integration Contracts
  type CostIntegrationTarget,
  type CostIntegrationContract,
  COST_INTEGRATION_CONTRACTS,

  // §10 — Query Functions
  getOptimizationRule,
  getOptimizationRulesByCategory,
  getOptimizationRulesByProvider,
  getAutoImplementableRules,
  getEnabledOptimizationRules,
  getCostPolicy,
  getProviderCostProfile,
  getCostPipelineStage,
  getCostPipelineOrder,
  getCostIntegration,
  estimateOptimizationSavings,

  // §11 — Tests
  type CostIntelligenceTestResult,
  runCostIntelligenceTests,
} from "./costIntelligence";

// ─────────────────────────────────────────────────────────────────────────────
// Compliance Engine
// Continuous compliance assessment against SOC2, HIPAA, PCI-DSS, CIS, NIST, GDPR
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Compliance Architecture
  type ComplianceFrameworkId,
  type ComplianceStatus,
  type ControlSeverity,
  type ComplianceFramework,
  type ControlFamily,
  COMPLIANCE_FRAMEWORKS as COMPLIANCE_ENGINE_FRAMEWORKS,

  // §2 — Control Definitions
  type ComplianceControl,
  type EvidenceType as ComplianceAuditEvidenceType,
  type CrossFrameworkMapping,
  COMPLIANCE_CONTROLS,

  // §3 — Assessment Model
  type ComplianceAssessment,
  type ComplianceScore,
  type FamilyScore,
  type SeverityScore,
  type ControlAssessmentResult,
  type ComplianceFinding,
  type FindingStatus,
  type EvidenceRecord,

  // §4 — Continuous Monitoring
  type ComplianceMonitorConfig,
  type ContinuousScanFrequency,
  type ComplianceDriftEvent,

  // §5 — Audit Readiness
  type AuditReadinessReport,
  type AuditGap,
  type EvidenceCompleteness,
  type RemediationBacklogSummary,
  type AuditRecommendation,

  // §6 — Compliance Pipeline
  type CompliancePipelineStageId,
  type CompliancePipelineStage,
  COMPLIANCE_PIPELINE,

  // §7 — Integration Contracts
  type ComplianceIntegrationTarget,
  type ComplianceIntegrationContract,
  COMPLIANCE_INTEGRATION_CONTRACTS,

  // §8 — Query Functions
  getComplianceFramework,
  getFrameworksByProvider,
  getCertificationRequiredFrameworks,
  getComplianceControl,
  getControlsByFramework,
  getControlsByFamily,
  getAutomatableControls,
  getCriticalControls,
  getControlsByProvider,
  getCrossFrameworkMappings,
  getCompliancePipelineStage,
  getCompliancePipelineOrder,
  getComplianceIntegration,
  computeComplianceScore,

  // §9 — Tests
  type ComplianceEngineTestResult,
  runComplianceEngineTests,
} from "./complianceEngine";

// ─────────────────────────────────────────────────────────────────────────────
// Notification & Communication Engine
// Multi-channel notification delivery with templates, routing, and digest aggregation
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Notification Architecture
  type NotificationChannel,
  type NotificationPriority,
  type NotificationCategory,
  type NotificationStatus,
  type Notification,
  type NotificationAction,
  type NotificationSourceEvent,

  // §2 — Templates
  type NotificationTemplate as NotificationChannelTemplate,
  type TemplateVariable,
  NOTIFICATION_TEMPLATES,

  // §3 — Channel Configuration
  type ChannelConfig,
  type RetryPolicy as NotificationRetryPolicy,
  CHANNEL_CONFIGS,

  // §4 — Routing Rules
  type NotificationRoutingRule,
  type RoutingCondition,
  DEFAULT_ROUTING_RULES,

  // §5 — Digest & Aggregation
  type DigestConfig,
  type DigestSection,
  DEFAULT_DIGEST_CONFIG,

  // §6 — User Preferences
  type UserNotificationPreferences,
  type QuietHoursConfig,
  type CategoryPreference,

  // §7 — Notification Pipeline
  type NotificationPipelineStageId,
  type NotificationPipelineStage,
  NOTIFICATION_PIPELINE,

  // §8 — Integration Contracts
  type NotificationIntegrationTarget,
  type NotificationIntegrationContract,
  NOTIFICATION_INTEGRATION_CONTRACTS,

  // §9 — Query Functions
  getNotificationTemplate,
  getTemplatesByCategory as getNotificationTemplatesByCategory,
  getTemplatesByChannel,
  getChannelConfig,
  getEnabledChannels,
  getChannelsForPriority,
  getRoutingRule,
  getEnabledRoutingRules,
  getNotificationPipelineStage,
  getNotificationPipelineOrder,
  getNotificationIntegration,

  // §10 — Tests
  type NotificationEngineTestResult,
  runNotificationEngineTests,
} from "./notificationEngine";

// ─────────────────────────────────────────────────────────────────────────────
// Cloud Event Stream Engine
// Real-time event ingestion from AWS/Azure/GCP with normalization, classification, and correlation
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Event Stream Architecture
  type CloudEventProvider,
  type CloudEventSourceType,
  type CloudEventSeverity,
  type CloudEventCategory,
  type CloudEvent,
  type EventUserIdentity,

  // §2 — Event Source Definitions
  type EventSourceConfig,
  type EventFilterPattern,
  type EventRetryPolicy,
  EVENT_SOURCE_CONFIGS,

  // §3 — Normalization Rules
  type EventNormalizationRule,
  type FieldExtractor,
  EVENT_NORMALIZATION_RULES,

  // §4 — Classification & Threat Intelligence
  type ThreatIndicatorType,
  type EventClassificationRule,
  type ClassificationCondition as EventClassificationCondition,
  EVENT_CLASSIFICATION_RULES,

  // §5 — Event Processing Pipeline
  type EventPipelineStageId,
  type EventPipelineStage,
  EVENT_PIPELINE,

  // §6 — Deduplication & Windowing
  type DeduplicationConfig,
  DEFAULT_DEDUP_CONFIG,
  type EventWindow,

  // §7 — Event Correlation
  type CorrelationStrategyType,
  type EventCorrelationRule,
  type CorrelationCondition as EventCorrelationCondition,
  EVENT_CORRELATION_RULES,

  // §8 — Stream Health & Backpressure
  type StreamHealthConfig,
  DEFAULT_STREAM_HEALTH_CONFIG,
  type StreamHealthSnapshot,
  type SourceHealthStatus,

  // §9 — Integration Contracts
  type EventStreamIntegrationTarget,
  type EventStreamIntegrationContract,
  EVENT_STREAM_INTEGRATION_CONTRACTS,

  // §10 — Query Functions
  getEventSourceConfig,
  getEventSourcesByProvider,
  getEnabledEventSources,
  getPollingEventSources,
  getWebhookEventSources,
  getNormalizationRule,
  getClassificationRule as getEventClassificationRule,
  getAutoEscalatingRules,
  getRulesWithMitreMapping,
  getClassificationRulesByProvider,
  getCorrelationRule as getEventCorrelationRule,
  getEventPipelineStage,
  getEventPipelineOrder,
  getEventStreamIntegration,
  computeEventPriority,

  // §11 — Tests
  type CloudEventStreamTestResult,
  runCloudEventStreamTests,
} from "./cloudEventStream";

// ─────────────────────────────────────────────────────────────────────────────
// Security Intelligence Engine
// Deep security posture analysis, IAM analysis, MITRE ATT&CK, vulnerability management
// ─────────────────────────────────────────────────────────────────────────────
export {
  // §1 — Security Posture Architecture
  type SecurityDomain,
  type SecurityPostureRating,
  type SecurityFindingSeverity,
  type SecurityFindingStatus,
  type SecurityPosture,
  type DomainSecurityScore,
  type FindingSummary,

  // §2 — Security Controls & Checks
  type SecurityControl as SecurityCheckControl,
  SECURITY_CONTROLS,

  // §3 — MITRE ATT&CK Integration
  type MitreTactic,
  type MitreTechniqueMapping,
  MITRE_CLOUD_TECHNIQUES,

  // §4 — Vulnerability Management
  type VulnerabilitySource,
  type VulnerabilityStatus,
  type VulnerabilityRecord,
  type VulnerabilityPolicy,
  DEFAULT_VULNERABILITY_POLICY,

  // §5 — IAM Analysis & Least Privilege
  type IAMRiskLevel,
  type IAMAnalysisRule,
  IAM_ANALYSIS_RULES,

  // §6 — Attack Surface Mapping
  type AttackSurfaceCategory,
  type AttackSurfaceComponent,
  type AttackSurfaceFactor,
  type AttackSurfaceSnapshot,
  type CategorySurfaceMetrics,

  // §7 — Security Recommendations
  type SecurityRecommendationPriority,
  type SecurityRecommendation,

  // §8 — Security Intelligence Pipeline
  type SecurityPipelineStageId,
  type SecurityPipelineStage,
  SECURITY_PIPELINE,

  // §9 — Integration Contracts
  type SecurityIntegrationTarget,
  type SecurityIntegrationContract,
  SECURITY_INTEGRATION_CONTRACTS,

  // §10 — Query Functions
  getSecurityControl,
  getControlsByDomain,
  getControlsByProvider as getSecurityControlsByProvider,
  getCriticalSecurityControls,
  getAutomatableSecurityControls,
  getMitreTechnique,
  getMitreTechniquesByTactic,
  getHighRelevanceTechniques,
  getIAMRule,
  getCriticalIAMRules,
  getIAMRulesByProvider,
  getSecurityPipelineStage,
  getSecurityPipelineOrder,
  getParallelizableSecurityStages,
  getSecurityIntegration,
  computePostureRating,
  computeVulnerabilitySLADeadline,

  // §11 — Tests
  type SecurityIntelligenceTestResult,
  runSecurityIntelligenceTests,
} from "./securityIntelligence";
