export type {
  RunAgentInput,
  ApprovalInput,
  AgentRunResult,
  AgentTrigger,
  AgentRunStatus,
  AgentFinding,
  FindingCategory,
  FindingSeverity,
  ActionDisposition,
  AgentRecommendation,
  AgentActionPlan,
  ApprovalItem,
  AgentApplyResult,
  AgentMessage,
  AgentMessageType,
} from "./types";

export { runAgent, handleApproval } from "./runAgent";
export { generateSnapshot } from "./providerRegistry";
export type { SnapshotGenerator } from "./providerRegistry";
export { classifyDisposition, findingToRecommendation, priorityScore, classifyDispositionWithPrefs, findingToRecommendationWithPrefs, priorityScoreWithPrefs } from "./prioritizer";
export { loadPreferences, savePreferences, filterIgnoredFindings, applyDispositionPolicy, applyRiskTolerance, categoryBoost, agentTone } from "./preferences";
export type { OrgPreferences, PreferenceUpdates } from "./preferences";
export { buildRecommendations } from "./recommendationBuilder";
export type { RichRecommendation } from "./recommendationBuilder";
export * as agentMessages from "./messageBuilder";
export { runFirstExperience } from "./onboarding";
export type { OnboardingInput, OnboardingSummary, OnboardingFinding, OnboardingNextStep } from "./onboarding";
export {
  resolvePolicy,
  resolveDisposition,
  applyAutopilotToRecommendations,
  changeAutopilotMode,
  logAutopilotAction,
  loadAutopilotMode,
  isEscalation,
  getModeConfirmationCopy,
  MODE_COPY,
  MODE_ORDER,
} from "./autopilot";
export type { AutopilotMode, AutopilotPolicy, AutopilotDecision, AutopilotModeCopy } from "./autopilot";
export { buildMultiCloudSummary } from "./multiCloudSummary";
export type { MultiCloudSummary, ProviderRunInput } from "./multiCloudSummary";
export { prioritizeMultiCloudRecommendations, runPrioritizerTests, SCORING_RULES } from "./multiCloudPrioritizer";
export type { PrioritizedRecommendation, MultiCloudRecommendationInput, ScoreBreakdown } from "./multiCloudPrioritizer";
export { runReasoningEngine, runReasoningTests, PROMPT_TEMPLATES } from "./reasoningEngine";
export type {
  ReasoningContext,
  PreviousRunSummary,
  Theme,
  ThemeTag,
  ThemeDisposition,
  Tradeoff,
  ReasonedOutput,
  TrendAnalysis,
} from "./reasoningEngine";
export {
  generateAgentPlan,
  buildDependencyGraph,
  topologicalSort,
  detectCycles,
  getReadyPhases,
  runPlanningTests,
  EXAMPLE_PLANS,
} from "./planningEngine";
export type {
  AgentPlan,
  PlanPhase,
  PlanStatus,
  PhaseStatus,
  RolloutArchetype,
  PhasingStrategy,
  PhaseType,
  PhaseImpact,
  PhasePrecondition,
  SuccessCriterion,
  RollbackTrigger,
  DependencyEdge,
  DependencyGraph,
  ApprovalCheckpoint,
  PlanImpact,
  PlanRollbackSummary,
  PlanGenerationInput,
} from "./planningEngine";
export {
  diffSnapshots,
  shouldSuppress,
  buildMonitorNotification,
  runMonitor,
  runMonitoringTests,
  ALL_RULES,
  DEFAULT_ALERT_POLICY,
} from "./monitoringAgent";
export type {
  AlertSeverity,
  AlertCategory,
  MonitorAlert,
  AlertDelta,
  SnapshotDelta,
  ResourceChange,
  FieldChange,
  ComputeDelta,
  StorageDelta,
  RegionDelta,
  CostDelta,
  FlagsDelta,
  DiffRule,
  MonitorContext,
  VerifiedItem,
  PreviousAlert,
  AlertPolicy,
  SnoozedRule,
  EscalationRule,
  SuppressionState,
  MonitorResult,
  SuppressedAlert,
  MonitorNotification,
  MonitoringTestResult,
} from "./monitoringAgent";
export {
  recordSignal,
  recordApproval,
  recordRejection,
  recordExport,
  getSignals,
  clearSignals,
  aggregateProfile,
  applyAdaptiveBehavior,
  adaptiveCategoryBoost,
  inferRiskTolerance,
  inferOutputPreference,
  resetAdaptiveBehavior,
  inspectAdaptiveBehavior,
  validateAdjustments,
  runAdaptiveTests,
  DEFAULT_ADAPTIVE_CONFIG,
} from "./adaptiveBehavior";
export type {
  SignalType,
  BehaviorSignal,
  BehaviorProfile,
  ActionTypeRate,
  CategoryRate,
  ProviderActivity,
  RiskApprovalDistribution,
  AdaptiveAdjustment,
  AdjustmentType,
  AdaptiveResult,
  AdaptiveConfig,
  RiskToleranceSuggestion,
  SafeguardCheck,
  AdaptiveTestResult,
} from "./adaptiveBehavior";
export {
  registerWorkflow,
  getWorkflow,
  listWorkflows,
  deleteWorkflow,
  enableWorkflow,
  disableWorkflow,
  getExecutionHistory,
  getOrgExecutionHistory,
  shouldTrigger,
  evaluateConditions,
  executeActions,
  executeWorkflow,
  fireEvent,
  runWorkflowTests,
  EXAMPLE_WORKFLOWS,
} from "./workflowEngine";
export type {
  Workflow,
  WorkflowTrigger,
  ScheduleTrigger,
  ScanCompletedTrigger,
  AlertFiredTrigger,
  ApprovalCompletedTrigger,
  ThresholdCrossedTrigger,
  ThresholdMetric,
  ManualTrigger,
  WorkflowCondition,
  FindingCountCondition,
  SavingsCondition,
  SeverityCondition,
  CategoryCondition,
  ProviderCondition,
  AlertCategoryCondition,
  RiskLevelCondition,
  TimeWindowCondition,
  WorkflowAction,
  RunScanAction,
  GeneratePlanAction,
  GenerateTerraformAction,
  GenerateCLIAction,
  SendNotificationAction,
  NotificationTemplate,
  ApplySafeFixesAction,
  CreateSummaryAction,
  TriggerContext,
  WorkflowMetrics,
  WorkflowExecution,
  ConditionResult,
  ActionResult,
  WorkflowTestResult,
} from "./workflowEngine";
export {
  hasPermission,
  getPermissions,
  isRoleAtLeast,
  canManageRole,
  isProviderInScope,
  authorize,
  resolveApprovalPolicy,
  resolveWithDefaults,
  createChain,
  getChain,
  getChainsForItem,
  getChainsForOrg,
  castVote,
  resolveChain,
  checkEscalation,
  logRbacEvent,
  getRbacAuditLog,
  authorizeAction,
  getPresetNames,
  loadPreset,
  runRbacTests,
  EXAMPLE_POLICIES,
  POLICY_PRESETS,
} from "./rbacEngine";
export type {
  Permission,
  Membership,
  AuthorizationResult,
  ApprovalPolicyDef,
  ApprovalTarget,
  PolicyMatch,
  ApprovalChain,
  ApprovalVote,
  VoteDecision,
  VoteInput,
  VoteResult,
  ChainResolution,
  EscalationCheck,
  RbacAuditEvent,
  RbacAuditAction,
  AuthorizationDecision,
  PolicyPreset,
  RbacTestResult,
} from "./rbacEngine";
export {
  generateCorrelationId,
  setLogLevel,
  addLogSink,
  removeAllSinks,
  addMetricSink,
  removeAllMetricSinks,
  log,
  getLogBuffer,
  clearLogBuffer,
  incCounter,
  setGauge,
  recordHistogram,
  getCounter,
  getGauge,
  getHistogram,
  getHistogramStats,
  resetMetrics,
  registerAlertRule,
  removeAlertRule,
  listAlertRules,
  getFiredAlerts,
  evaluateAlertRules,
  getHealthCheck,
  exportMetrics,
  logRunStarted,
  logRunCompleted,
  logRunFailed,
  logConnectorAuth,
  logConnectorFetch,
  logSnapshotQuality,
  logTerraformGenerated,
  logTerraformFailed,
  logApplyStarted,
  logApplySuccess,
  logApplyFailed,
  logRollback,
  logVerification,
  logNotification,
  logWorkflow,
  logMonitorAlert,
  runObservabilityTests,
  DASHBOARDS,
  DEFAULT_ALERT_RULES,
} from "./observability";
export type {
  CorrelationContext,
  LogLevel,
  LogCategory,
  StructuredLogEntry,
  MetricType,
  MetricName,
  MetricTags,
  HistogramStats,
  AlertSeverityLevel,
  AlertRule,
  AlertCondition,
  AlertChannel,
  FiredAlert,
  HealthStatus,
  HealthCheck,
  ComponentHealth,
  DashboardPanel,
  Dashboard,
  MetricsSnapshot,
  ObservabilityTestResult,
} from "./observability";
