import type { CloudSnapshot } from "../cloudSnapshot";

export const awsSnapshot: CloudSnapshot = {
  provider: "aws",
  accountId: "123456789012",
  scannedAt: "2026-05-03T14:00:00Z",
  regions: ["us-east-1", "us-west-2"],
  monthlySpend: 2400,
  flags: { singleRegion: false, noBackupsDetected: false },
  resources: [
    {
      resourceType: "compute",
      provider: "aws",
      resourceId: "i-0a1b2c3d4e5f",
      region: "us-east-1",
      instanceType: "m5.2xlarge",
      tier: "general",
      vcpus: 8,
      memoryGb: 32,
      state: "running",
      usage: { cpuAvgPct: 12, sampleWindowHours: 168 },
      monthlyCostEstimate: 280,
    },
    {
      resourceType: "compute",
      provider: "aws",
      resourceId: "i-0f6e7d8c9b0a",
      region: "us-east-1",
      instanceType: "c5.xlarge",
      tier: "compute",
      vcpus: 4,
      memoryGb: 8,
      state: "running",
      usage: { cpuAvgPct: 68, sampleWindowHours: 168 },
      monthlyCostEstimate: 124,
    },
    {
      resourceType: "storage",
      provider: "aws",
      resourceId: "logs-prod",
      region: "us-east-1",
      storageClass: "standard",
      sizeGb: 420,
      objectCount: 12_000_000,
      lastAccessedDaysAgo: 45,
      monthlyCostEstimate: 9.66,
    },
    {
      resourceType: "storage",
      provider: "aws",
      resourceId: "assets-cdn",
      region: "us-east-1",
      storageClass: "standard",
      sizeGb: 85,
      objectCount: 340_000,
      monthlyCostEstimate: 1.96,
    },
  ],
};

export const azureSnapshot: CloudSnapshot = {
  provider: "azure",
  accountId: "sub-a1b2c3d4-e5f6-7890",
  scannedAt: "2026-05-03T14:00:00Z",
  regions: ["eastus"],
  monthlySpend: 1800,
  flags: { singleRegion: true, noBackupsDetected: true },
  resources: [
    {
      resourceType: "compute",
      provider: "azure",
      resourceId: "vm-api-prod-01",
      region: "eastus",
      instanceType: "Standard_D4s_v3",
      tier: "general",
      vcpus: 4,
      memoryGb: 16,
      state: "running",
      usage: { cpuAvgPct: 22, memoryAvgPct: 41, sampleWindowHours: 168 },
      monthlyCostEstimate: 140,
    },
    {
      resourceType: "compute",
      provider: "azure",
      resourceId: "vm-worker-03",
      region: "eastus",
      instanceType: "Standard_D8s_v3",
      tier: "general",
      vcpus: 8,
      memoryGb: 32,
      state: "running",
      usage: { cpuAvgPct: 9, memoryAvgPct: 18, sampleWindowHours: 168 },
      monthlyCostEstimate: 280,
    },
    {
      resourceType: "compute",
      provider: "azure",
      resourceId: "vm-staging-01",
      region: "eastus",
      instanceType: "Standard_D2s_v3",
      tier: "general",
      vcpus: 2,
      memoryGb: 8,
      state: "deallocated",
      monthlyCostEstimate: 0,
    },
    {
      resourceType: "storage",
      provider: "azure",
      resourceId: "stprodlogs",
      region: "eastus",
      storageClass: "standard",
      sizeGb: 600,
      monthlyCostEstimate: 12.60,
    },
  ],
};

export const gcpSnapshot: CloudSnapshot = {
  provider: "gcp",
  accountId: "my-project-prod-42",
  scannedAt: "2026-05-03T14:00:00Z",
  regions: ["us-central1", "europe-west1"],
  flags: { singleRegion: false, noBackupsDetected: false },
  resources: [
    {
      resourceType: "compute",
      provider: "gcp",
      resourceId: "api-server-group-a1b2",
      region: "us-central1",
      instanceType: "n2-standard-8",
      tier: "general",
      vcpus: 8,
      memoryGb: 32,
      state: "running",
      usage: { cpuAvgPct: 35, sampleWindowHours: 168 },
      monthlyCostEstimate: 245,
    },
    {
      resourceType: "compute",
      provider: "gcp",
      resourceId: "ml-trainer-c3d4",
      region: "us-central1",
      instanceType: "n1-highmem-16",
      tier: "memory",
      vcpus: 16,
      memoryGb: 104,
      state: "running",
      usage: { cpuAvgPct: 72, sampleWindowHours: 168 },
      monthlyCostEstimate: 580,
    },
    {
      resourceType: "storage",
      provider: "gcp",
      resourceId: "data-lake-raw",
      region: "us-central1",
      storageClass: "standard",
      sizeGb: 2400,
      monthlyCostEstimate: 49.20,
    },
  ],
};
