/**
 * Country list utility - loads all ISO countries
 * Matches iOS CountryPickerView.loadCountries() logic
 */

export interface CountryInfo {
  name: string;
  code: string;
}

/**
 * Load all ISO countries
 * Matches iOS CountryPickerView.loadCountries() logic
 */
export function loadAllCountries(): CountryInfo[] {
  const countries: CountryInfo[] = [];
  
  // Common country codes that are likely to be used (matching iOS common countries)
  const countryMap: Record<string, string> = {
    // Popular countries with specific guidance
    "India": "IN",
    "Pakistan": "PK",
    "Philippines": "PH",
    "Bangladesh": "BD",
    "Nepal": "NP",
    "Mexico": "MX",
    "China": "CN",
    "Nigeria": "NG",
    "Vietnam": "VN",
    "Brazil": "BR",
    "Colombia": "CO",
    "Jamaica": "JM",
    "Haiti": "HT",
    "Dominican Republic": "DO",
    "South Korea": "KR",
    "Japan": "JP",
    "United Kingdom": "GB",
    "Canada": "CA",
    "Australia": "AU",
    "South Africa": "ZA",
    "Ethiopia": "ET",
    "Thailand": "TH",
    "Sri Lanka": "LK",
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Argentina": "AR",
    "Armenia": "AM",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bulgaria": "BG",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Chile": "CL",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Estonia": "EE",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Guatemala": "GT",
    "Guyana": "GY",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Liberia": "LR",
    "Libya": "LY",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Mauritius": "MU",
    "Moldova": "MD",
    "Mongolia": "MN",
    "Morocco": "MA",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "North Korea": "KP",
    "Norway": "NO",
    "Oman": "OM",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Somalia": "SO",
    "Spain": "ES",
    "Sudan": "SD",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela": "VE",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
  };
  
  // Convert to array and sort
  for (const [name, code] of Object.entries(countryMap)) {
    countries.push({ name, code });
  }
  
  // Sort by name
  return countries.sort((a, b) => a.name.localeCompare(b.name));
}
