/**
 * Terraform Generator — produces .tf files from a MultiCloudReadinessReport.
 * Phase 4: Active-Passive only. AWS primary → Azure secondary.
 * Generates minimal, safe infrastructure: resource group, vnet, storage, DNS placeholder.
 */

import { prisma } from "@/lib/db";
import path from "path";
import fs from "fs/promises";
import os from "os";

export interface GenerateOptions {
  leadId: string;
  userId?: string | null;
  readinessReportId: string;
  mode: "active_passive";
  secondaryCloud: "azure";
}

export interface GeneratedTerraform {
  jobId: string;
  workingDirectory: string;
  files: Record<string, string>;
}

function generateMainTf(projectName: string): string {
  return `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.80"
    }
  }
}

provider "azurerm" {
  features {}

  tenant_id       = var.azure_tenant_id
  client_id       = var.azure_client_id
  client_secret   = var.azure_client_secret
  subscription_id = var.azure_subscription_id
}

# --- Resource Group ---
resource "azurerm_resource_group" "standby" {
  name     = "\${var.project_name}-standby-rg"
  location = var.azure_region

  tags = {
    managed_by  = "ai-cloud-operator"
    project     = var.project_name
    mode        = "active-passive"
    role        = "standby"
    environment = var.environment
  }
}

# --- Virtual Network ---
resource "azurerm_virtual_network" "standby" {
  name                = "\${var.project_name}-standby-vnet"
  location            = azurerm_resource_group.standby.location
  resource_group_name = azurerm_resource_group.standby.name
  address_space       = [var.vnet_address_space]

  tags = azurerm_resource_group.standby.tags
}

resource "azurerm_subnet" "standby_default" {
  name                 = "default"
  resource_group_name  = azurerm_resource_group.standby.name
  virtual_network_name = azurerm_virtual_network.standby.name
  address_prefixes     = [var.subnet_address_prefix]
}

# --- Storage Account (standby data sync target) ---
resource "azurerm_storage_account" "standby" {
  name                     = replace("\${var.project_name}standbysa", "-", "")
  resource_group_name      = azurerm_resource_group.standby.name
  location                 = azurerm_resource_group.standby.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"

  blob_properties {
    versioning_enabled = true
  }

  tags = azurerm_resource_group.standby.tags
}
`;
}

function generateVariablesTf(): string {
  return `variable "project_name" {
  description = "Project identifier used for resource naming"
  type        = string
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "standby"
}

variable "azure_tenant_id" {
  description = "Azure AD Tenant ID"
  type        = string
  sensitive   = true
}

variable "azure_client_id" {
  description = "Azure Service Principal Client ID"
  type        = string
  sensitive   = true
}

variable "azure_client_secret" {
  description = "Azure Service Principal Client Secret"
  type        = string
  sensitive   = true
}

variable "azure_subscription_id" {
  description = "Azure Subscription ID"
  type        = string
  sensitive   = true
}

variable "azure_region" {
  description = "Azure region for standby infrastructure"
  type        = string
  default     = "eastus"
}

variable "vnet_address_space" {
  description = "CIDR block for the standby VNet"
  type        = string
  default     = "10.1.0.0/16"
}

variable "subnet_address_prefix" {
  description = "CIDR block for the default subnet"
  type        = string
  default     = "10.1.0.0/24"
}
`;
}

function generateTfvars(projectName: string): string {
  return `# Generated by AI Cloud Operator
# Fill in Azure credentials before running terraform plan

project_name = "${projectName}"
environment  = "standby"

# Azure credentials (from your linked Azure connector)
# azure_tenant_id       = ""
# azure_client_id       = ""
# azure_client_secret   = ""
# azure_subscription_id = ""

azure_region          = "eastus"
vnet_address_space    = "10.1.0.0/16"
subnet_address_prefix = "10.1.0.0/24"
`;
}

function generateOutputsTf(): string {
  return `output "resource_group_name" {
  description = "Name of the standby resource group"
  value       = azurerm_resource_group.standby.name
}

output "resource_group_id" {
  description = "ID of the standby resource group"
  value       = azurerm_resource_group.standby.id
}

output "vnet_name" {
  description = "Name of the standby virtual network"
  value       = azurerm_virtual_network.standby.name
}

output "vnet_id" {
  description = "ID of the standby virtual network"
  value       = azurerm_virtual_network.standby.id
}

output "storage_account_name" {
  description = "Name of the standby storage account"
  value       = azurerm_storage_account.standby.name
}

output "storage_account_id" {
  description = "ID of the standby storage account"
  value       = azurerm_storage_account.standby.id
}
`;
}

function sanitizeProjectName(leadId: string): string {
  return leadId.replace(/[^a-z0-9]/gi, "").slice(0, 20).toLowerCase() || "project";
}

export async function generateTerraform(opts: GenerateOptions): Promise<GeneratedTerraform> {
  const report = await prisma.multiCloudReadinessReport.findUnique({
    where: { id: opts.readinessReportId },
  });
  if (!report) throw new Error("Readiness report not found");
  if (report.leadId !== opts.leadId) throw new Error("Report does not belong to this project");

  if (opts.mode !== "active_passive") throw new Error("Only active_passive mode is supported");
  if (opts.secondaryCloud !== "azure") throw new Error("Only Azure secondary is supported in this phase");

  const projectName = sanitizeProjectName(opts.leadId);

  const files: Record<string, string> = {
    "main.tf": generateMainTf(projectName),
    "variables.tf": generateVariablesTf(),
    "terraform.tfvars": generateTfvars(projectName),
    "outputs.tf": generateOutputsTf(),
  };

  const workDir = path.join(os.tmpdir(), "ai-cloud-operator", `tf-${opts.leadId}-${Date.now()}`);
  await fs.mkdir(workDir, { recursive: true });

  for (const [filename, content] of Object.entries(files)) {
    await fs.writeFile(path.join(workDir, filename), content, "utf-8");
  }

  const job = await prisma.terraformExecutionJob.create({
    data: {
      leadId: opts.leadId,
      userId: opts.userId ?? null,
      readinessReportId: opts.readinessReportId,
      status: "generating",
      mode: opts.mode,
      primaryCloud: "aws",
      secondaryCloud: opts.secondaryCloud,
      workingDirectory: workDir,
      generatedFiles: Object.fromEntries(
        Object.entries(files).map(([k, v]) => [k, v.length > 5000 ? `${v.slice(0, 5000)}...[truncated]` : v])
      ) as object,
    },
  });

  await prisma.terraformExecutionJob.update({
    where: { id: job.id },
    data: { status: "generating" },
  });

  return { jobId: job.id, workingDirectory: workDir, files };
}
