/**
 * Metrics taxonomy + in-process counters.
 *
 * The platform doesn't yet ship with Prometheus / StatsD. This module gives
 * every subsystem one place to increment named counters and inspect rolling
 * totals — the Reliability/Observability centers read from here, and a
 * future exporter can wire stdout/Prom/OTel without changing call sites.
 *
 * Counters are tenant-scoped where the metric depends on a tenant (scans,
 * findings, exports, audit). Counters that describe the *platform* (auth
 * failures, redaction events) are not — they roll up across tenants.
 */

import type { OrganizationId } from "@/lib/domain/ids";

// ---------------------------------------------------------------------------
// Metric taxonomy
// ---------------------------------------------------------------------------

export type MetricId =
  // Cloud / scans
  | "cloud.scan.started"
  | "cloud.scan.completed"
  | "cloud.scan.failed"
  | "cloud.scan.duration_ms"
  | "cloud.findings.generated"
  | "cloud.recommendations.generated"
  | "cloud.provider.validation_failed"
  | "cloud.provider.rate_limited"
  // Execution
  | "execution.plan.generated"
  | "execution.plan.exported"
  | "execution.approval.pending"
  | "execution.approval.granted"
  | "execution.approval.denied"
  | "execution.rollback.prepared"
  | "execution.verification.completed"
  // ReleaseOps
  | "releaseops.repo.discovered"
  | "releaseops.workflow.analyzed"
  | "releaseops.readiness.recomputed"
  | "releaseops.deployment.blocker"
  | "releaseops.github.sync_failed"
  // Reliability
  | "reliability.workflow.failed"
  | "reliability.job.retried"
  | "reliability.deadletter.created"
  | "reliability.circuit.opened"
  | "reliability.provider.degraded"
  // Security
  | "security.policy.blocked"
  | "security.rbac.denied"
  | "security.tenant.cross_attempt"
  | "security.credential.validation_failed"
  | "security.redaction.applied"
  // Desktop
  | "desktop.connection.attempted"
  | "desktop.handoff.prepared"
  | "desktop.sync.failed"
  | "desktop.platform.available"
  // Copilot
  | "copilot.query.received"
  | "copilot.query.blocked"
  | "copilot.response.modified_by_guardrail";

export type MetricUnit = "count" | "ms" | "bytes";

export interface MetricSpec {
  id: MetricId;
  unit: MetricUnit;
  description: string;
  /** True iff this metric varies per tenant. */
  tenantScoped: boolean;
}

export const METRIC_SPECS: Record<MetricId, MetricSpec> = {
  // Cloud
  "cloud.scan.started":           { id: "cloud.scan.started",           unit: "count", description: "Cloud scans started.",                              tenantScoped: true },
  "cloud.scan.completed":         { id: "cloud.scan.completed",         unit: "count", description: "Cloud scans completed successfully.",               tenantScoped: true },
  "cloud.scan.failed":            { id: "cloud.scan.failed",            unit: "count", description: "Cloud scans that ended in failure.",                tenantScoped: true },
  "cloud.scan.duration_ms":       { id: "cloud.scan.duration_ms",       unit: "ms",    description: "Cumulative scan duration in milliseconds.",         tenantScoped: true },
  "cloud.findings.generated":     { id: "cloud.findings.generated",     unit: "count", description: "Findings generated by the signal engine.",          tenantScoped: true },
  "cloud.recommendations.generated": { id: "cloud.recommendations.generated", unit: "count", description: "Recommendations attached to findings.",        tenantScoped: true },
  "cloud.provider.validation_failed": { id: "cloud.provider.validation_failed", unit: "count", description: "Provider credential validations that failed.", tenantScoped: true },
  "cloud.provider.rate_limited":  { id: "cloud.provider.rate_limited",  unit: "count", description: "Provider responses signalling rate limit.",         tenantScoped: true },
  // Execution
  "execution.plan.generated":     { id: "execution.plan.generated",     unit: "count", description: "Execution plan candidates generated.",              tenantScoped: true },
  "execution.plan.exported":      { id: "execution.plan.exported",      unit: "count", description: "Execution plans exported (Terraform/CLI).",         tenantScoped: true },
  "execution.approval.pending":   { id: "execution.approval.pending",   unit: "count", description: "Approvals awaiting review.",                        tenantScoped: true },
  "execution.approval.granted":   { id: "execution.approval.granted",   unit: "count", description: "Approvals granted.",                                tenantScoped: true },
  "execution.approval.denied":    { id: "execution.approval.denied",    unit: "count", description: "Approvals denied.",                                  tenantScoped: true },
  "execution.rollback.prepared":  { id: "execution.rollback.prepared",  unit: "count", description: "Rollback plans prepared.",                          tenantScoped: true },
  "execution.verification.completed": { id: "execution.verification.completed", unit: "count", description: "Verification checks completed.",            tenantScoped: true },
  // ReleaseOps
  "releaseops.repo.discovered":   { id: "releaseops.repo.discovered",   unit: "count", description: "Repos discovered in ReleaseOps sync.",              tenantScoped: true },
  "releaseops.workflow.analyzed": { id: "releaseops.workflow.analyzed", unit: "count", description: "CI workflows analysed.",                            tenantScoped: true },
  "releaseops.readiness.recomputed": { id: "releaseops.readiness.recomputed", unit: "count", description: "Readiness score recomputations.",             tenantScoped: true },
  "releaseops.deployment.blocker": { id: "releaseops.deployment.blocker", unit: "count", description: "Deployment blockers raised.",                     tenantScoped: true },
  "releaseops.github.sync_failed": { id: "releaseops.github.sync_failed", unit: "count", description: "GitHub sync failures.",                           tenantScoped: true },
  // Reliability
  "reliability.workflow.failed":  { id: "reliability.workflow.failed",  unit: "count", description: "Workflow runs that ended in failure.",              tenantScoped: true },
  "reliability.job.retried":      { id: "reliability.job.retried",      unit: "count", description: "Jobs that triggered a retry.",                      tenantScoped: true },
  "reliability.deadletter.created": { id: "reliability.deadletter.created", unit: "count", description: "Items placed into the dead-letter queue.",     tenantScoped: true },
  "reliability.circuit.opened":   { id: "reliability.circuit.opened",   unit: "count", description: "Circuit breaker transitions to open.",              tenantScoped: true },
  "reliability.provider.degraded": { id: "reliability.provider.degraded", unit: "count", description: "Provider health observations marked degraded.",    tenantScoped: true },
  // Security
  "security.policy.blocked":      { id: "security.policy.blocked",      unit: "count", description: "Actions blocked by policy.",                        tenantScoped: true },
  "security.rbac.denied":         { id: "security.rbac.denied",         unit: "count", description: "RBAC permission denials.",                          tenantScoped: true },
  "security.tenant.cross_attempt": { id: "security.tenant.cross_attempt", unit: "count", description: "Cross-tenant access attempts blocked.",           tenantScoped: false },
  "security.credential.validation_failed": { id: "security.credential.validation_failed", unit: "count", description: "Credential validation failures.", tenantScoped: true },
  "security.redaction.applied":   { id: "security.redaction.applied",   unit: "count", description: "Strings that triggered the redaction pipeline.",    tenantScoped: false },
  // Desktop
  "desktop.connection.attempted": { id: "desktop.connection.attempted", unit: "count", description: "Desktop pairing attempts.",                          tenantScoped: true },
  "desktop.handoff.prepared":     { id: "desktop.handoff.prepared",     unit: "count", description: "Desktop handoff payloads prepared.",                tenantScoped: true },
  "desktop.sync.failed":          { id: "desktop.sync.failed",          unit: "count", description: "Desktop audit sync failures.",                      tenantScoped: true },
  "desktop.platform.available":   { id: "desktop.platform.available",   unit: "count", description: "Desktop availability probes succeeding.",           tenantScoped: false },
  // Copilot
  "copilot.query.received":       { id: "copilot.query.received",       unit: "count", description: "Copilot queries received.",                         tenantScoped: true },
  "copilot.query.blocked":        { id: "copilot.query.blocked",        unit: "count", description: "Copilot queries blocked by intent classifier.",     tenantScoped: true },
  "copilot.response.modified_by_guardrail": { id: "copilot.response.modified_by_guardrail", unit: "count", description: "Copilot responses modified by outbound guardrail.", tenantScoped: true },
};

// ---------------------------------------------------------------------------
// In-process counter store
// ---------------------------------------------------------------------------

interface CounterKey {
  metric: MetricId;
  tenant?: OrganizationId;
}

function compositeKey(key: CounterKey): string {
  return `${key.metric}::${key.tenant ?? "_platform"}`;
}

const _counters = new Map<string, number>();

export interface RecordOptions {
  /** Required for tenant-scoped metrics. */
  organizationId?: OrganizationId;
  /** Increment by this much. Defaults to 1. */
  by?: number;
}

export function record(metric: MetricId, opts: RecordOptions = {}): void {
  const spec = METRIC_SPECS[metric];
  if (!spec) return;
  const tenant = spec.tenantScoped ? opts.organizationId : undefined;
  if (spec.tenantScoped && !tenant) {
    // Tenant-scoped metrics without a tenant land in a "_unknown" bucket so
    // we can spot the gap rather than silently swallowing the signal.
    const key = compositeKey({ metric, tenant: "_unknown" as unknown as OrganizationId });
    _counters.set(key, (_counters.get(key) ?? 0) + (opts.by ?? 1));
    return;
  }
  const key = compositeKey({ metric, tenant });
  _counters.set(key, (_counters.get(key) ?? 0) + (opts.by ?? 1));
}

export function reset(): void { _counters.clear(); }

export interface CounterSnapshot {
  metric: MetricId;
  tenant?: OrganizationId;
  value: number;
  unit: MetricUnit;
  description: string;
}

/** Read a single counter — used by the Observability Center UI. */
export function read(metric: MetricId, tenant?: OrganizationId): CounterSnapshot {
  const spec = METRIC_SPECS[metric];
  const t = spec.tenantScoped ? tenant : undefined;
  const value = _counters.get(compositeKey({ metric, tenant: t })) ?? 0;
  return { metric, tenant: t, value, unit: spec.unit, description: spec.description };
}

/** Read every counter for a tenant (or platform-wide). */
export function readAll(tenant?: OrganizationId): CounterSnapshot[] {
  return (Object.keys(METRIC_SPECS) as MetricId[]).map((m) => read(m, tenant));
}

/** Read every counter for a tenant grouped by domain prefix. */
export function readGrouped(tenant?: OrganizationId): Record<string, CounterSnapshot[]> {
  const groups: Record<string, CounterSnapshot[]> = {};
  for (const snap of readAll(tenant)) {
    const prefix = snap.metric.split(".")[0];
    (groups[prefix] ?? (groups[prefix] = [])).push(snap);
  }
  return groups;
}
