/**
 * Action executor — Phase 644.
 *
 * Consumes engineer outputs (typically an approver_engineer
 * packet) and fires a real, observable action against the
 * customer's integrations.
 *
 * Supported actions (this phase):
 *   · github_issue       — opens a GitHub issue with finding +
 *                          recommended remediation + audit
 *                          correlation id
 *   · slack_action_post  — posts a structured Slack message to
 *                          the configured action webhook
 *
 * Each dispatch persists an ActionExecutionRow at
 * targetKind=workforce_action_execution so the operator + audit
 * trail can see every action the platform took.
 *
 * Failure handling: every dispatch returns a structured result
 * (never throws to the caller). HTTP failures are captured;
 * credential-resolution failures surface a clear hint.
 *
 * Server-only.
 */

import "server-only";

import { prisma } from "@/lib/db";
import {
  readIntegrationConfig,
  resolveCredentialReferenceAsync,
  type GitHubIntegration,
  type SlackActionIntegration,
} from "@/lib/workforce/domains/integrationRegistry";

export const ACTION_EXECUTION_TARGET_KIND = "workforce_action_execution";

export type ActionKind = "github_issue" | "slack_action_post";

export interface ActionPayload {
  title: string;
  body: string;
  /** Distinguishes "open issue" vs "comment on issue" if we add
   *  follow-up actions later. For now everything is "create". */
  mode?: "create";
  /** Optional labels in addition to the integration's default
   *  issue_label. */
  extraLabels?: ReadonlyArray<string>;
  /** Correlation id from the upstream engineer (approval packet
   *  slug, etc.) — surfaced in the action so the operator can
   *  trace it back. */
  upstreamRef?: string;
}

export type ExecutionStatus = "executed" | "skipped" | "failed";

export interface ExecutionResult {
  status: ExecutionStatus;
  /** When status=executed, the external id the integration
   *  returned (GitHub issue url, Slack message ts, etc.). */
  externalRef: string | null;
  /** Human-readable result line for the audit row + UI. */
  detail: string;
  errorCode: string | null;
}

const MAX_TITLE = 240;
const MAX_BODY = 32000;

function sanitizeTitle(s: string): string {
  return s.replace(/[\r\n]+/g, " ").slice(0, MAX_TITLE);
}

function buildIssueBody(payload: ActionPayload): string {
  const lines: string[] = [];
  lines.push(payload.body.slice(0, MAX_BODY));
  if (payload.upstreamRef) {
    lines.push("");
    lines.push("---");
    lines.push(`_Generated by visionxixlabs · upstream ref: \`${payload.upstreamRef}\`_`);
  }
  return lines.join("\n");
}

async function executeGithubIssue(
  integration: GitHubIntegration,
  payload: ActionPayload,
): Promise<ExecutionResult> {
  if (!integration.enabled) {
    return { status: "skipped", externalRef: null, detail: "github integration paused", errorCode: "integration_paused" };
  }
  if (!integration.repo || !integration.repo.includes("/")) {
    return { status: "failed", externalRef: null, detail: "github repo not configured", errorCode: "repo_missing" };
  }
  const resolved = await resolveCredentialReferenceAsync(integration.patReference);
  if (!resolved.ok) {
    return {
      status: "failed",
      externalRef: null,
      detail: `github PAT could not be resolved from ${integration.patReference}: ${resolved.error.detail}`,
      errorCode: `pat_${resolved.error.errorCode}`,
    };
  }
  const pat = resolved.value;

  const labels = [integration.issueLabel, ...(payload.extraLabels ?? [])].filter(Boolean).slice(0, 10);
  const url = `https://api.github.com/repos/${integration.repo}/issues`;

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "visionxixlabs-action-executor/1.0",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: sanitizeTitle(payload.title),
        body: buildIssueBody(payload),
        labels,
      }),
      signal: AbortSignal.timeout(15_000),
    });
    if (!res.ok) {
      const errText = await res.text().catch(() => "(no body)");
      return {
        status: "failed",
        externalRef: null,
        detail: `github responded ${res.status}: ${errText.slice(0, 200)}`,
        errorCode: `http_${res.status}`,
      };
    }
    const json = await res.json().catch(() => null) as { html_url?: string; number?: number } | null;
    const externalRef = json?.html_url ?? (json?.number ? `#${json.number}` : null);
    return {
      status: "executed",
      externalRef,
      detail: `github issue created: ${externalRef ?? "unknown ref"}`,
      errorCode: null,
    };
  } catch (e) {
    return {
      status: "failed",
      externalRef: null,
      detail: e instanceof Error ? e.message.slice(0, 200) : "unknown error",
      errorCode: "fetch_failed",
    };
  }
}

async function executeSlackPost(
  integration: SlackActionIntegration,
  payload: ActionPayload,
): Promise<ExecutionResult> {
  if (!integration.enabled) {
    return { status: "skipped", externalRef: null, detail: "slack actions paused", errorCode: "integration_paused" };
  }
  if (!integration.webhookUrl || !integration.webhookUrl.startsWith("https://hooks.slack.com/")) {
    return { status: "failed", externalRef: null, detail: "slack webhook url invalid", errorCode: "webhook_invalid" };
  }
  try {
    const res = await fetch(integration.webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: payload.title,
        blocks: [
          { type: "header", text: { type: "plain_text", text: sanitizeTitle(payload.title), emoji: true } },
          { type: "section", text: { type: "mrkdwn", text: payload.body.slice(0, 2900) } },
          ...(payload.upstreamRef
            ? [{
                type: "context",
                elements: [{ type: "mrkdwn", text: `_upstream ref: \`${payload.upstreamRef}\`_` }],
              }]
            : []),
        ],
      }),
      signal: AbortSignal.timeout(8_000),
    });
    if (!res.ok) {
      return {
        status: "failed",
        externalRef: null,
        detail: `slack responded ${res.status}`,
        errorCode: `http_${res.status}`,
      };
    }
    return { status: "executed", externalRef: null, detail: "slack message posted", errorCode: null };
  } catch (e) {
    return {
      status: "failed",
      externalRef: null,
      detail: e instanceof Error ? e.message.slice(0, 200) : "unknown error",
      errorCode: "fetch_failed",
    };
  }
}

/**
 * Persist one ActionExecutionRow per dispatch so the operator can
 * audit every action the platform took. Returns the slug for
 * UI/audit linking.
 */
async function persistExecution(
  organizationId: string,
  kind: ActionKind,
  payload: ActionPayload,
  result: ExecutionResult,
): Promise<string> {
  const slug = `${kind}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const tags: string[] = [
    `kind|${kind}`,
    `status|${result.status}`,
    `title|${sanitizeTitle(payload.title)}`,
    `detail|${result.detail.slice(0, 400)}`,
  ];
  if (result.externalRef) tags.push(`external_ref|${result.externalRef}`);
  if (result.errorCode) tags.push(`error_code|${result.errorCode}`);
  if (payload.upstreamRef) tags.push(`upstream_ref|${payload.upstreamRef}`);

  try {
    await prisma.aiRationaleEnrichment.upsert({
      where: {
        organizationId_targetKind_targetId: {
          organizationId,
          targetKind: ACTION_EXECUTION_TARGET_KIND,
          targetId: slug,
        },
      },
      create: {
        organizationId,
        targetKind: ACTION_EXECUTION_TARGET_KIND,
        targetId: slug,
        narrative: `${kind} :: ${result.status} :: ${result.detail.slice(0, 240)}`,
        riskFactorsJson: [] as unknown as string[],
        nextActionsJson: tags as unknown as string[],
        outcome: result.status === "executed" ? "ai_generated" : result.status === "skipped" ? "fallback_rules" : "error",
        errorMessage: result.errorCode,
        modelHint: null,
        engineVersion: "action-executor-v1",
      },
      update: {
        narrative: `${kind} :: ${result.status} :: ${result.detail.slice(0, 240)}`,
        nextActionsJson: tags as unknown as string[],
        outcome: result.status === "executed" ? "ai_generated" : result.status === "skipped" ? "fallback_rules" : "error",
        errorMessage: result.errorCode,
      },
    });
  } catch (e) {
    console.warn("[actionExecutor] persist failed:", e instanceof Error ? e.message : e);
  }
  return slug;
}

/**
 * Decide whether a signed approval packet should fan out to the
 * action executor. Pure rule, so the gate is testable without DB.
 *
 * Rule: only dispatch when the packet was actually signed (decision=
 * "approve") AND it's high-stakes — broader than workspace OR not
 * fully reversible. Fully-reversible workspace-only auto-approvals
 * would flood the channel.
 */
export function shouldDispatchApproval(p: {
  recommendedDecision: string;
  impactRadius: string;
  reversibility: string;
}): { dispatch: boolean; reason: string } {
  if (p.recommendedDecision !== "approve") {
    return { dispatch: false, reason: `decision=${p.recommendedDecision}` };
  }
  const broaderThanWorkspace = p.impactRadius === "tenant" || p.impactRadius === "org" || p.impactRadius === "global";
  const notFullyReversible = p.reversibility !== "fully";
  if (!broaderThanWorkspace && !notFullyReversible) {
    return { dispatch: false, reason: "low_stakes_workspace_reversible" };
  }
  return { dispatch: true, reason: "high_stakes_signed" };
}

/**
 * Fan out an approval packet to every configured integration.
 * Each leg is best-effort — a Slack 500 must not block the GitHub
 * issue from opening, and a missing integration must not be an error.
 */
export async function dispatchApprovalActions(
  organizationId: string,
  packet: {
    slug: string;
    title: string;
    executiveSummary: string;
    proposalSummary: string;
    impactRadius: string;
    decisionAuthority: string;
    reversibility: string;
    recommendedDecision: string;
    approvalChecklist: ReadonlyArray<string>;
  },
): Promise<ReadonlyArray<{ kind: ActionKind; result: ExecutionResult; executionSlug: string }>> {
  const gate = shouldDispatchApproval(packet);
  if (!gate.dispatch) return [];

  const upstreamRef = `${ACTION_EXECUTION_TARGET_KIND}:${packet.slug}`;
  const checklist = packet.approvalChecklist.length === 0
    ? ""
    : ["", "Approval checklist:", ...packet.approvalChecklist.map((c) => `- [ ] ${c}`)].join("\n");
  const body = [
    `**Decision:** ${packet.recommendedDecision} (authority: ${packet.decisionAuthority})`,
    `**Impact:** ${packet.impactRadius} · **Reversibility:** ${packet.reversibility}`,
    "",
    "**Executive summary:**",
    packet.executiveSummary,
    "",
    "**Proposal:**",
    packet.proposalSummary,
    checklist,
  ].filter(Boolean).join("\n");

  const sharedPayload: ActionPayload = {
    title: `[approver] ${packet.title}`,
    body,
    upstreamRef,
  };

  const results: Array<{ kind: ActionKind; result: ExecutionResult; executionSlug: string }> = [];
  const [github, slack] = await Promise.all([
    dispatchAction(organizationId, "github_issue", sharedPayload),
    dispatchAction(organizationId, "slack_action_post", sharedPayload),
  ]);
  results.push({ kind: "github_issue", ...github });
  results.push({ kind: "slack_action_post", ...slack });
  return results;
}

/**
 * Dispatch an action. Reads the workspace's integration config,
 * routes to the matching integration handler, persists the result.
 */
export async function dispatchAction(
  organizationId: string,
  kind: ActionKind,
  payload: ActionPayload,
): Promise<{ result: ExecutionResult; executionSlug: string }> {
  const config = await readIntegrationConfig(organizationId);
  let result: ExecutionResult;
  switch (kind) {
    case "github_issue":
      if (!config.github) {
        result = { status: "skipped", externalRef: null, detail: "github integration not configured", errorCode: "not_configured" };
      } else {
        result = await executeGithubIssue(config.github, payload);
      }
      break;
    case "slack_action_post":
      if (!config.slackActions) {
        result = { status: "skipped", externalRef: null, detail: "slack actions integration not configured", errorCode: "not_configured" };
      } else {
        result = await executeSlackPost(config.slackActions, payload);
      }
      break;
    default:
      result = { status: "failed", externalRef: null, detail: `unknown action kind: ${String(kind)}`, errorCode: "unknown_kind" };
  }
  const executionSlug = await persistExecution(organizationId, kind, payload, result);
  return { result, executionSlug };
}
