/**
 * Terraform plan renderer — the first real executor in the platform.
 *
 * Generates a copy-paste-ready Terraform HCL fragment for an approved
 * AxiomApprovalItem. The HCL is NOT applied — the operator downloads
 * it, reviews it, and runs `terraform plan && terraform apply` in
 * their own environment. This is a safe-by-default executor: nothing
 * mutates AWS until a human actively chooses to.
 *
 * Coverage today: AWS only, mapped from the ActionType enum the schema
 * supports. Each branch produces a self-contained HCL fragment with a
 * provider block, a target resource block, and a comment header
 * explaining what the plan does + how to apply it.
 *
 * Future: add Azure / GCP branches, add per-action import blocks so
 * Terraform doesn't try to create resources that already exist.
 */

type ActionType =
  | "resize_compute"
  | "apply_storage_policy"
  | "purchase_commitment"
  | "decommission_compute";

type Provider = "aws" | "azure" | "gcp";

export interface ApprovalLike {
  id: string;
  title: string;
  actionType: ActionType;
  provider: Provider;
  region: string;
  resourceIds: ReadonlyArray<string>;
  currentState: string;
  recommendedState: string;
  riskLevel: "low" | "medium" | "high";
  dispositionReason: string;
}

const TERRAFORM_DISCLAIMER = `# ─────────────────────────────────────────────────────────────────
# This plan was generated by Axiom and NOT applied automatically.
# Review every block, then run from a clean working directory:
#
#   terraform init
#   terraform plan
#   terraform apply
#
# All resource addresses use 'imported_' prefixes — if you already
# manage these resources elsewhere, replace with your own addresses
# or use 'terraform import' to bring them under management first.
# ─────────────────────────────────────────────────────────────────`;

export function renderTerraformPlan(item: ApprovalLike): string {
  const header = [
    TERRAFORM_DISCLAIMER,
    "",
    `# ${item.title}`,
    `# Action: ${item.actionType.replace(/_/g, " ")}`,
    `# Risk:   ${item.riskLevel}`,
    `# Reason: ${item.dispositionReason}`,
    `# Item:   ${item.id}`,
    "",
  ].join("\n");

  const providerBlock = renderProviderBlock(item.provider, item.region);
  const resourceBlocks = renderResourceBlocks(item);

  return [header, providerBlock, "", resourceBlocks].join("\n");
}

function renderProviderBlock(provider: Provider, region: string): string {
  switch (provider) {
    case "aws":
      return [
        `terraform {`,
        `  required_providers {`,
        `    aws = {`,
        `      source  = "hashicorp/aws"`,
        `      version = "~> 5.0"`,
        `    }`,
        `  }`,
        `}`,
        ``,
        `provider "aws" {`,
        `  region = "${escape(region)}"`,
        `}`,
      ].join("\n");
    case "azure":
      return [
        `terraform {`,
        `  required_providers {`,
        `    azurerm = {`,
        `      source  = "hashicorp/azurerm"`,
        `      version = "~> 3.0"`,
        `    }`,
        `  }`,
        `}`,
        ``,
        `provider "azurerm" {`,
        `  features {}`,
        `}`,
      ].join("\n");
    case "gcp":
      return [
        `terraform {`,
        `  required_providers {`,
        `    google = {`,
        `      source  = "hashicorp/google"`,
        `      version = "~> 5.0"`,
        `    }`,
        `  }`,
        `}`,
        ``,
        `provider "google" {`,
        `  region = "${escape(region)}"`,
        `}`,
      ].join("\n");
  }
}

function renderResourceBlocks(item: ApprovalLike): string {
  if (item.resourceIds.length === 0) {
    return `# No specific resource targets — review the finding and apply your fix manually.`;
  }

  // AWS coverage is the only one wired today; other providers fall
  // through to a generic 'review manually' comment.
  if (item.provider !== "aws") {
    return [
      `# ${item.provider.toUpperCase()} plan rendering is not implemented yet.`,
      `# Resource targets from the scan:`,
      ...item.resourceIds.map((r) => `#   - ${r}`),
    ].join("\n");
  }

  switch (item.actionType) {
    case "apply_storage_policy":
      // Default mapping until the recommendation engine produces real
      // action types — close public S3 ACLs is the canonical example.
      return item.resourceIds.map((bucket, i) => `
# Block public access on ${bucket}
resource "aws_s3_bucket_public_access_block" "imported_${safeName(bucket, i)}" {
  bucket = "${stripArnPrefix(bucket)}"

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}`.trim()).join("\n\n");

    case "resize_compute":
      return item.resourceIds.map((arn, i) => `
# Resize ${arn}
# Current: ${escape(item.currentState)}
# Target:  ${escape(item.recommendedState)}
resource "aws_instance" "imported_${safeName(arn, i)}" {
  # Bring under management first:
  #   terraform import aws_instance.imported_${safeName(arn, i)} ${stripArnPrefix(arn)}
  instance_type = "${escape(item.recommendedState)}"
  # Other required attributes (ami, subnet_id, etc.) — pull from your
  # current resource and add here before running 'terraform apply'.
}`.trim()).join("\n\n");

    case "decommission_compute":
      return [
        `# Decommission the following resources by removing the corresponding`,
        `# resource blocks from your Terraform state. Run 'terraform plan' to`,
        `# see the destroy actions; then 'terraform apply' to execute.`,
        ``,
        ...item.resourceIds.map((arn, i) => `# resource "aws_instance" "imported_${safeName(arn, i)}" { /* delete this block */ }   # ${arn}`),
      ].join("\n");

    case "purchase_commitment":
      return [
        `# Reserved capacity / commitment purchases are not represented in`,
        `# Terraform state. Use the AWS console or CLI:`,
        ``,
        ...item.resourceIds.map((r) => `#   aws ec2 purchase-reserved-instances-offering --reserved-instances-offering-id ${stripArnPrefix(r)} --instance-count 1`),
      ].join("\n");
  }
}

function safeName(input: string, fallbackIndex: number): string {
  const cleaned = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned.length > 0 ? cleaned.slice(0, 60) : `item_${fallbackIndex + 1}`;
}

function stripArnPrefix(input: string): string {
  // Bucket names, instance ids etc. are usually the last ARN segment.
  if (input.startsWith("arn:")) {
    return input.split(/[/:]/).pop() ?? input;
  }
  return input;
}

function escape(s: string): string {
  // Minimal HCL string escape — backslash + double quote.
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
